---
permalink: sm-storage/add-member-volumes-to-a-snapshot-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, member, volume, snapshot consistency group 
summary: Você pode adicionar um novo volume membro a um grupo de consistência de snapshot. Ao adicionar um novo volume membro, você também deve reservar capacidade para o volume membro. 
---
= Adicione um volume membro a um grupo de consistência de Snapshot no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar um novo volume membro a um grupo de consistência de snapshot. Ao adicionar um novo volume membro, você também deve reservar capacidade para o volume membro.

.Antes de começar
* O volume de membro deve ser Optimal.
* O grupo de consistência de Snapshot deve ter menos volumes do que o número máximo permitido (conforme definido na sua configuração).
* Cada volume de capacidade reservada deve ter as mesmas configurações de Data Assurance (DA) e segurança que o volume membro associado.


.Sobre esta tarefa
Você pode adicionar volumes padrão ou volumes finos ao grupo de consistência de Snapshot. O volume base pode residir em um pool ou grupo de volume.

.Passos
. Selecione o menu: storage[Snapshots].
. Selecione a guia *Snapshot Consistency Groups*.
+
A tabela é exibida e mostra todos os grupos de consistência de Snapshot associados ao array de storage.

. Selecione o grupo de consistência de Snapshot que deseja modificar e clique em *Adicionar membros*.
+
A caixa de diálogo Adicionar membros é exibida.

. Selecione o(s) volume(s) de membro que deseja adicionar e, em seguida, clique em *Avançar*.
+
A etapa Capacidade de Reserva é exibida. A tabela Candidatos a Volume mostra apenas os candidatos que suportam a capacidade de reserva especificada.

. Use a caixa de rotação para alocar a capacidade reservada para o volume do membro. Execute uma das seguintes ações:
+
** *Aceite as configurações padrão.*
+
Utilize esta opção recomendada para alocar a capacidade reservada para o volume de membro com as configurações padrão.

** *Aloque suas próprias configurações de capacidade reservada para atender às suas necessidades de storage de dados.*
+
Se você alterar a configuração padrão de capacidade reservada, clique em *Atualizar candidatos* para atualizar a lista de candidatos para a capacidade reservada que você especificou.

+
Aloque a capacidade reservada usando as seguintes diretrizes.

+
*** A configuração padrão para capacidade reservada é 40% da capacidade do volume base, e geralmente essa capacidade é suficiente.
*** A capacidade necessária varia dependendo da frequência e do tamanho das gravações de E/S nos volumes e da quantidade e duração da coleta de imagens de Snapshot.




. Clique em *Concluir* para adicionar os volumes de membro.

