---
permalink: sm-storage/add-to-workload.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add workload, volume 
summary: Você pode adicionar um ou mais volumes a uma carga de trabalho existente ou nova para volumes que não estejam atualmente associados a uma carga de trabalho. 
---
= Adicionar volumes a uma carga de trabalho no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar um ou mais volumes a uma carga de trabalho existente ou nova para volumes que não estejam atualmente associados a uma carga de trabalho.

.Sobre esta tarefa
Os volumes não são associados a uma carga de trabalho se tiverem sido criados usando a interface de linha de comando (CLI) ou se tiverem sido migrados (importados/exportados) de um array de storage diferente.

.Passos
. Selecione o menu: storage [Volumes].
. Selecione a guia *Applications & Workloads*.
+
A visualização Applications & Workloads é exibida.

. Selecione *Add to Workload*.
+
A caixa de diálogo Select Workload é exibida.

. Execute uma das seguintes ações:
+
** *Adicionar volumes a uma carga de trabalho existente* -- selecione esta opção para adicionar volumes a uma carga de trabalho existente.
+
Use a lista suspensa para selecionar uma carga de trabalho. O tipo de aplicativo associado à carga de trabalho é atribuído aos volumes que você adiciona a essa carga de trabalho.

** *Adicionar volumes a uma nova carga de trabalho* -- Selecione esta opção para definir uma nova carga de trabalho para um tipo de aplicação e adicionar volumes à nova carga de trabalho.


. Selecione *Avançar* para continuar com a sequência de adição à workload.
+
A caixa de diálogo Selecionar Volumes é exibida.

. Selecione os volumes que deseja adicionar à carga de trabalho.
. Analise os volumes que você deseja adicionar à carga de trabalho selecionada.
. Quando estiver satisfeito com a configuração da sua carga de trabalho, clique em *Finish*.

