---
permalink: sm-storage/assign-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, assign volumes 
summary: Você deve atribuir um volume a um host ou a um cluster de hosts para que ele possa ser usado em operações de E/S. Essa atribuição concede a um host ou a um cluster de hosts acesso a um ou mais volumes em um array de storage. 
---
= Atribuir volumes aos hosts no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve atribuir um volume a um host ou a um cluster de hosts para que ele possa ser usado em operações de E/S. Essa atribuição concede a um host ou a um cluster de hosts acesso a um ou mais volumes em um array de storage.

.Sobre esta tarefa
Tenha em mente estas diretrizes ao atribuir volumes aos hosts:

* Você pode atribuir um volume a apenas um host ou cluster de hosts por vez.
* Os volumes atribuídos são compartilhados entre os controladores no array de storage.
* O mesmo número de unidade lógica (LUN) não pode ser usado duas vezes por um host ou um cluster de hosts para acessar um volume. Você deve usar um LUN exclusivo.
* Para novos grupos de volumes, se você esperar até que todos os volumes sejam criados e inicializados antes de atribuí-los a um host, o tempo de inicialização do volume será reduzido. Lembre-se de que, uma vez que um volume associado ao grupo de volume seja mapeado, _todos_ os volumes retornarão à inicialização mais lenta. Você pode verificar o progresso da inicialização em menu:Início[Operações em Andamento].


A atribuição de um volume falha sob estas condições:

* Todos os volumes estão atribuídos.
* O volume já está atribuído a outro host ou cluster de hosts.


A possibilidade de atribuir um volume não está disponível nestas condições:

* Não existem hosts ou host clusters válidos.
* Nenhum identificador de porta de host foi definido para o host.
* Todas as atribuições de volume foram definidas.


Todos os volumes não atribuídos são exibidos durante esta tarefa, mas as funções para hosts com ou sem Data Assurance (DA) aplicam-se da seguinte forma:

* Para um host compatível com DA, você pode selecionar volumes que estejam habilitados para DA ou que não estejam habilitados para DA.
* Para um host que não seja compatível com DA, se você selecionar um volume que esteja habilitado para DA, um aviso informa que o sistema deve desativar automaticamente o DA no volume antes de atribuir o volume ao host.


.Passos
. Selecione o menu: storage [Hosts].
. Selecione o host ou cluster de hosts ao qual deseja atribuir volumes e clique em *Assign Volumes*.
+
Uma caixa de diálogo é exibida que lista todos os volumes que podem ser atribuídos. Você pode classificar qualquer uma das colunas ou digitar algo na caixa *Filtro* para facilitar a localização de volumes específicos.

. Selecione a caixa de seleção ao lado de cada volume que você deseja atribuir ou selecione a caixa de seleção no cabeçalho da tabela para selecionar todos os volumes.
. Clique em *Assign* para concluir a operação.


.Resultados
Após atribuir com sucesso um volume ou volumes a um host ou um cluster de hosts, o sistema executa as seguintes ações:

* O volume atribuído recebe o próximo número LUN disponível. O host usa o número LUN para acessar o volume.
* O nome do volume fornecido pelo usuário aparece nas listagens de volumes associadas ao host. Se aplicável, o volume de acesso configurado de fábrica também aparece nas listagens de volumes associadas ao host.

