---
permalink: sm-storage/change-settings-for-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, volume 
summary: Você pode alterar as configurações de um volume, como seu nome, atribuição de host, tamanho do segmento, prioridade de modificação, armazenamento em cache e assim por diante. 
---
= Altere as configurações de um volume no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar as configurações de um volume, como seu nome, atribuição de host, tamanho do segmento, prioridade de modificação, armazenamento em cache e assim por diante.

.Antes de começar
O volume que você deseja alterar está no status Ótimo.


NOTE: Algumas operações podem estar indisponíveis enquanto as alterações nas configurações do volume estiverem em andamento

.Passos
. Selecione o menu: storage [Volumes].
. Selecione o volume que você deseja alterar e, em seguida, selecione *View/Edit Settings*.
+
A caixa de diálogo Configurações de Volume é exibida. As configurações do volume que você selecionou aparecem nessa caixa de diálogo.

. Selecione a guia *Básico* para alterar o nome do volume e a atribuição do host.
+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Configuração | Descrição 


 a| 
Nome
 a| 
Exibe o nome do volume. Altere o nome de um volume quando o nome atual não for mais significativo ou aplicável.



 a| 
Capacidades
 a| 
Exibe a capacidade reportada e alocada para o volume selecionado.

A capacidade reportada e a capacidade alocada são as mesmas para volumes espessos, mas são diferentes para volumes finos. Para um volume espesso, o espaço fisicamente alocado é igual ao espaço reportado ao host. Para um volume fino, a capacidade reportada é a capacidade que é reportada aos hosts, enquanto a capacidade alocada é a quantidade de espaço em disco que está atualmente alocada para gravação de dados.



 a| 
Pool / grupo de volume
 a| 
Exibe o nome e o nível RAID do pool ou grupo de volume. Indica se o pool ou grupo de volume é compatível com segurança e se está com a segurança habilitada.



 a| 
Host
 a| 
Exibe a atribuição de volume. Você atribui um volume a um host ou cluster de hosts para que ele possa ser acessado para operações de E/S. Essa atribuição concede a um host ou cluster de hosts acesso a um volume específico ou a vários volumes em um array de storage.

** *Atribuído a* -- Identifica o host ou cluster de hosts que tem acesso ao volume selecionado.
** *LUN* -- Um número de unidade lógica (LUN) é o número atribuído ao espaço de endereçamento que um host usa para acessar um volume. O volume é apresentado ao host como capacidade na forma de um LUN. Cada host tem seu próprio espaço de endereçamento LUN. Portanto, o mesmo LUN pode ser usado por diferentes hosts para acessar volumes diferentes.
+

NOTE: Para interfaces NVMe, esta coluna exibe o Namespace ID. Um namespace é um armazenamento NVM formatado para acesso em bloco. É análogo a uma unidade lógica em SCSI, que se relaciona a um volume no array de storage. O Namespace ID é o identificador exclusivo do controlador NVMe para o namespace e pode ser definido com um valor entre 1 e 255. É análogo a um número de unidade lógica (LUN) em SCSI.





 a| 
Identificadores
 a| 
Exibe os identificadores do volume selecionado.

** *Identificador mundial (WWID)* -- um identificador hexadecimal único para o volume.
** *Identificador único estendido (EUI)* -- Um identificador EUI-64 para o volume.
** *Identificador de subsistema (SSID)* -- O identificador do subsistema do array de storage de um volume.


|===
====
. Selecione a guia *Advanced* para alterar configurações adicionais de um volume em um pool ou em um grupo de volume.
+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Configuração | Descrição 


 a| 
Informações sobre aplicativo e carga de trabalho
 a| 
Durante a criação de volume, você pode criar cargas de trabalho específicas para aplicativos ou outras cargas de trabalho. Se aplicável, o nome da carga de trabalho, o tipo de aplicativo e o tipo de volume aparecem para o volume selecionado.

Você pode alterar o nome da carga de trabalho se desejar.



 a| 
Configurações de qualidade de serviço
 a| 
*Desativar permanentemente data assurance* -- Esta configuração só aparece se o volume tiver data assurance (DA) ativada. DA verifica e corrige erros que podem ocorrer durante a transferência de dados pelos controladores até as unidades. Use esta opção para desativar permanentemente DA no volume selecionado. Quando desativada, DA não poderá ser reativada neste volume.

*Habilitar verificação de redundância pré-leitura* -- Esta configuração só aparece se o volume for um volume espesso. As verificações de redundância pré-leitura determinam se os dados em um volume são consistentes sempre que uma leitura é realizada. Um volume com este recurso habilitado retorna erros de leitura se os dados forem considerados inconsistentes pelo firmware do controlador.



 a| 
Propriedade do controlador
 a| 
Define o controlador que é designado para ser o proprietário ou controlador principal do volume.

A gestão dos controladores é muito importante e deve ser planejada cuidadosamente. Os controladores devem ser distribuídos da forma mais equilibrada possível para o total de I/Os.



 a| 
Dimensionamento de segmentos
 a| 
Exibe a configuração de dimensionamento de segmento, que aparece apenas para volumes em um grupo de volume. Você pode alterar o tamanho do segmento para otimizar o desempenho.

*Transições de tamanho de segmento permitidas* -- System Manager determina as transições de tamanho de segmento permitidas. Tamanhos de segmento que representam transições inadequadas em relação ao tamanho atual não estão disponíveis na lista suspensa. Transições permitidas geralmente são o dobro ou a metade do tamanho atual do segmento. Por exemplo, se o tamanho atual do segmento de volume for 32 KiB, um novo tamanho de segmento de volume de 16 KiB ou 64 KiB é permitido.

*Volumes com SSD Cache habilitado* -- Você pode especificar um tamanho de segmento de 4 KiB para volumes com SSD Cache habilitado. Certifique-se de selecionar o tamanho de segmento de 4 KiB somente para volumes com SSD Cache habilitado que lidam com operações de E/S de blocos pequenos (por exemplo, tamanhos de bloco de E/S de 16 KiB ou menores). O desempenho pode ser afetado se você selecionar 4 KiB como tamanho de segmento para volumes com SSD Cache habilitado que lidam com operações sequenciais de blocos grandes.

*Tempo necessário para alterar o tamanho do segmento* -- O tempo necessário para alterar o tamanho do segmento de um volume depende destas variáveis:

** A carga de E/S do host
** A prioridade de modificação do volume
** O número de unidades no grupo de volume
** O número de canais de drive
** O poder de processamento dos controladores do array de storage. Ao alterar o tamanho do segmento de um volume, o desempenho de E/S é afetado, mas seus dados permanecem disponíveis.




 a| 
Prioridade de modificação
 a| 
Mostra a configuração de prioridade de modificação, que só aparece para volumes em um grupo de volume.

A prioridade de modificação define quanto tempo de processamento é alocado para operações de modificação de volume em relação ao desempenho do sistema. Você pode aumentar a prioridade de modificação de volume, embora isso possa afetar o desempenho do sistema.

Mova as barras deslizantes para selecionar um nível de prioridade.

*Taxas de prioridade de modificação* -- A taxa de prioridade mais baixa beneficia o desempenho do sistema, mas a operação de modificação leva mais tempo. A taxa de prioridade mais alta beneficia a operação de modificação, mas o desempenho do sistema pode ser comprometido.



 a| 
Armazenamento em cache
 a| 
Exibe a configuração de armazenamento em cache, que você pode alterar para afetar o desempenho geral de E/S de um volume.



 a| 
Cache SSD
 a| 
Exibe a configuração de cache SSD, que você pode ativar em volumes compatíveis como uma forma de melhorar o desempenho somente de leitura. Os volumes são compatíveis se compartilharem as mesmas capacidades de Drive Security e Data Assurance.

*O recurso de cache SSD utiliza um ou mais discos de estado sólido (SSDs) para implementar um cache de leitura*. O desempenho dos aplicativos é aprimorado devido aos tempos de leitura mais rápidos dos SSDs. Como o cache de leitura está no array de storage, o armazenamento em cache é compartilhado entre todos os aplicativos que utilizam o array de storage. Basta selecionar o volume que você deseja armazenar em cache, e então o armazenamento em cache será automático e dinâmico.

|===
====
. Clique em *Salvar*.
+
System Manager altera as configurações do volume com base nas suas seleções.



.Depois que você terminar
Selecione o menu: Home [View Operations in Progress] para visualizar o progresso das operações de alteração que estão sendo executadas no momento para o volume selecionado.
