---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-consistency-group-member-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, consistency group, member volume 
summary: Você pode alterar as configurações de um volume membro de grupo de consistência para ajustar a porcentagem em que System Manager envia uma notificação de alerta quando a capacidade reservada para um volume membro estiver quase cheia e para alterar a política a ser usada quando a capacidade reservada atingir sua porcentagem máxima definida. 
---
= Altere as configurações de capacidade reservada para um volume membro de grupo de consistência no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar as configurações de um volume membro de grupo de consistência para ajustar a porcentagem em que o SANtricity System Manager envia uma notificação de alerta quando a capacidade reservada para um volume membro estiver quase cheia e para alterar a política a ser usada quando a capacidade reservada atingir sua porcentagem máxima definida.

.Sobre esta tarefa
Alterar as configurações de capacidade reservada para um volume de membro individual também altera as configurações de capacidade reservada para todos os volumes de membro associados a um grupo de consistência.

.Passos
. Selecione o menu: Storage [Pools & Volume Groups].
. Clique na guia *Capacidade Reservada*.
. Selecione o volume membro do grupo de consistência que você deseja editar e clique em *Exibir/Editar configurações*.
+
A caixa de diálogo Configurações de Capacidade Reservada do Volume do Membro é exibida.

. Altere as configurações de capacidade reservada para o volume de membro conforme apropriado.
+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Configuração | Descrição 


 a| 
Avise-me quando...
 a| 
Use o seletor giratório para ajustar o ponto percentual em que System Manager envia uma notificação de alerta quando a capacidade reservada para um volume de membro estiver quase cheia.

Quando a capacidade reservada para o volume do membro excede o limite especificado, System Manager envia um alerta, permitindo que você aumente a capacidade reservada ou exclua objetos desnecessários.


NOTE: Alterar a configuração de alerta para um volume membro alterará para _todos_ os volumes membros que pertencem ao mesmo grupo de consistência.



 a| 
Política para capacidade totalmente reservada
 a| 
Você pode escolher uma das seguintes políticas:

** *Excluir imagem de Snapshot mais antiga* -- System Manager exclui automaticamente a imagem de Snapshot mais antiga no grupo de consistência, o que libera a capacidade reservada do membro para reutilização dentro do grupo.
** *Rejeitar gravações no volume base* -- Quando a capacidade reservada atinge a porcentagem máxima definida, System Manager rejeita qualquer solicitação de gravação de E/S para o volume base que acionou o acesso à capacidade reservada.


|===
====
. Clique em *Salvar* para aplicar suas alterações.


.Resultados
System Manager altera as configurações de capacidade reservada para o volume membro, bem como as configurações de capacidade reservada para todos os volumes membros no grupo de consistência.
