---
permalink: sm-storage/change-the-settings-for-a-snapshot-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, snapshot, consistency group 
summary: Altere as configurações de um grupo de consistência de Snapshot quando desejar alterar seu nome, as configurações de exclusão automática ou o número máximo de imagens de Snapshot permitidas. 
---
= Altere as configurações de um grupo de consistência no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Altere as configurações de um grupo de consistência de Snapshot quando desejar alterar seu nome, as configurações de exclusão automática ou o número máximo de imagens de Snapshot permitidas.

.Passos
. Selecione o menu: storage[Snapshots].
. Clique na guia *Snapshot Consistency Groups*.
. Selecione o grupo de consistência do Snapshot que você deseja editar e clique em *Exibir/Editar configurações*.
+
A caixa de diálogo Configuração do Grupo de Consistência do Snapshot é exibida.

. Altere as configurações do grupo de consistência do Snapshot conforme necessário.
+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Configuração | Descrição 


 a| 
*Configurações do grupo de consistência do Snapshot*



 a| 
Nome
 a| 
Você pode alterar o nome do grupo de consistência do Snapshot.



 a| 
Exclusão automática
 a| 
Mantenha a caixa de seleção marcada se desejar que as imagens de Snapshot sejam excluídas automaticamente após o limite especificado; use a caixa de rotação para alterar o limite. Se você desmarcar esta caixa de seleção, a criação de imagens de Snapshot será interrompida após 32 imagens.



 a| 
Limite de imagens do Snapshot
 a| 
Você pode alterar o número máximo de imagens de Snapshot permitidas para um grupo de Snapshot.



 a| 
Agendamento do Snapshot
 a| 
Este campo indica se um agendamento está associado ao grupo de consistência do Snapshot.



 a| 
*Objetos associados*



 a| 
Volumes de membro
 a| 
Você pode visualizar a quantidade de volumes de membros associados ao grupo de consistência do Snapshot.

|===
====
. Clique em *Salvar*.

