---
permalink: sm-storage/change-configuration-settings-for-a-pool.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configuration settings, pool 
summary: Você pode editar as configurações de um pool, incluindo seu nome, configurações de alertas de capacidade, prioridades de modificação e capacidade de preservação. 
---
= Altere as configurações de um pool no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode editar as configurações de um pool, incluindo seu nome, configurações de alertas de capacidade, prioridades de modificação e capacidade de preservação.

.Sobre esta tarefa
Esta tarefa descreve como alterar as configurações de um pool.

[NOTE]
====
Não é possível alterar o nível RAID de um pool usando a interface do System Manager. System Manager configura automaticamente os pools como RAID 6.

====
.Passos
. Selecione o menu: Storage [Pools & Volume Groups].
. Selecione o pool que você deseja editar e clique em *Visualizar/Editar Configurações*.
+
A caixa de diálogo Pool Setting é exibida.

. Selecione a aba *Configurações* e, em seguida, edite as configurações do pool conforme apropriado.
+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Configuração | Descrição 


 a| 
Nome
 a| 
Você pode alterar o nome do pool fornecido pelo usuário. É obrigatório especificar um nome para o pool.



 a| 
Alertas de capacidade
 a| 
Você pode enviar notificações de alerta quando a capacidade livre em um pool atingir ou ultrapassar um limite especificado. Quando os dados armazenados no pool ultrapassam o limite especificado, System Manager envia uma mensagem, permitindo que você adicione mais espaço de storage ou exclua objetos desnecessários.

Os alertas são exibidos na área de Notificações do Dashboard e podem ser enviados do servidor para os administradores por e-mail e mensagens SNMP trap.

Você pode definir os seguintes alertas de capacidade:

** *Alerta crítico* -- Este alerta crítico notifica você quando a capacidade livre no pool atinge ou ultrapassa o limite especificado. Use os controles giratórios para ajustar a porcentagem do limite. Selecione a caixa de seleção para desativar esta notificação.
** *Alerta antecipado* -- Este alerta antecipado notifica você quando a capacidade livre em um pool está atingindo um limite especificado. Use os controles giratórios para ajustar a porcentagem do limite. Selecione a caixa de seleção para desativar esta notificação.




 a| 
Prioridades de modificação
 a| 
Você pode especificar os níveis de prioridade para operações de modificação em um pool em relação ao desempenho do sistema. Uma prioridade mais alta para operações de modificação em um pool faz com que uma operação seja concluída mais rapidamente, mas pode diminuir o desempenho de I/O do host. Uma prioridade mais baixa faz com que as operações demorem mais, mas o desempenho de I/O do host é menos afetado.

Você pode escolher entre cinco níveis de prioridade: lowest, low, medium, high e highest. Quanto maior o nível de prioridade, maior é o impacto nas operações de E/S do host e no desempenho do sistema.

** *Prioridade crítica de reconstrução* -- Esta barra deslizante determina a prioridade de uma operação de reconstrução de dados quando múltiplas falhas de unidade resultam em uma condição na qual alguns dados não possuem redundância e uma falha adicional de unidade pode resultar em perda de dados.
** *Prioridade de reconstrução degradada* -- Esta barra deslizante determina a prioridade da operação de reconstrução de dados quando ocorre uma falha na unidade, mas os dados ainda possuem redundância e uma falha adicional na unidade não resulta em perda de dados.
** *Prioridade de operações em segundo plano* -- Esta barra deslizante determina a prioridade das operações em segundo plano do pool que ocorrem enquanto o pool está em um estado ideal. Essas operações incluem Dynamic Volume Expansion (DVE), Instant Availability Format (IAF) e migração de dados para uma unidade substituída ou adicionada.




 a| 
Capacidade de preservação ("Capacidade de otimização" para o EF600 ou EF300)
 a| 
*Capacidade de preservação* -- Você pode definir o número de unidades para determinar a capacidade reservada no pool para suportar possíveis falhas de unidade. Quando ocorre uma falha de unidade, a capacidade de preservação é usada para armazenar os dados reconstruídos. Os pools usam a capacidade de preservação durante o processo de reconstrução de dados em vez de hot spare, que são usados em grupos de volume.

Use os controles giratórios para ajustar o número de unidades. Com base no número de unidades, a capacidade de preservação no pool aparece ao lado da caixa do controle giratório.

Tenha em mente as seguintes informações sobre capacidade de preservação.

** Como a capacidade de preservação é subtraída da capacidade livre total de um pool, a quantidade de capacidade que você reserva afeta quanto de capacidade livre está disponível para criar volumes. Se você especificar 0 para a capacidade de preservação, toda a capacidade livre do pool é usada para a criação de volumes.
** Se você diminuir a capacidade de preservação, aumentará a capacidade que pode ser usada para volumes do pool.


*Capacidade de otimização adicional* (EF600 e EF300 arrays only) -- Quando um pool é criado, uma capacidade de otimização recomendada é gerada, proporcionando um equilíbrio entre capacidade disponível versus desempenho e vida útil dos discos. Você pode ajustar esse equilíbrio movendo o controle deslizante para a direita para melhor desempenho e vida útil dos discos em detrimento de maior capacidade disponível, ou movendo-o para a esquerda para maior capacidade disponível em detrimento de melhor desempenho e vida útil dos discos.

Unidades SSD terão uma vida útil mais longa e melhor desempenho máximo de gravação quando uma parte de sua capacidade estiver não alocada. Para unidades associadas a um pool, a capacidade não alocada é composta pela capacidade de preservação do pool, a capacidade livre (capacidade não usada pelos volumes) e uma parte da capacidade utilizável reservada como capacidade de otimização adicional. A capacidade de otimização adicional garante um nível mínimo de capacidade de otimização ao reduzir a capacidade utilizável e, assim, não está disponível para criação de volumes.

|===
====
. Clique em *Salvar*.

