---
permalink: sm-storage/change-the-settings-for-a-snapshot-schedule.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, snapshot, schedule 
summary: Para um agendamento do Snapshot, você pode alterar os horários de coleta automática ou a frequência da coleta. 
---
= Altere as configurações de um agendamento do Snapshot no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para um agendamento do Snapshot, você pode alterar os horários de coleta automática ou a frequência da coleta.

.Sobre esta tarefa
Você pode importar configurações de um agendamento do Snapshot existente ou pode modificar as configurações conforme necessário.

Como um agendamento do Snapshot está associado a um grupo de Snapshot ou grupo de consistência de Snapshot, a capacidade reservada pode ser afetada por alterações nas configurações de agendamento.

.Passos
. Selecione o menu: storage[Snapshots].
. Clique na aba *Schedules*.
. Selecione o agendamento do Snapshot que você deseja alterar e clique em *Editar*.
+
A caixa de diálogo Editar agendamento do Snapshot é exibida.

. Faça uma das seguintes ações:
+
** *Use um agendamento previamente definido de outro objeto de Snapshot* -- Clique em *Importar agendamento*, selecione o objeto com o agendamento que deseja importar e clique em *Importar*.
** *Edite as configurações de agendamento* -- Consulte os detalhes do campo abaixo.
+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Configuração | Descrição 


 a| 
Dia / mês
 a| 
Escolha uma das seguintes opções:

*** *Diário / Semanal* -- Selecione dias individuais para sincronização de Snapshots. Você também pode selecionar a caixa de seleção *Selecionar todos os dias* no canto superior direito se desejar um agendamento diário.
*** *Mensal / Anual* -- Selecione meses individuais para snapshots de sincronização. No campo *Em dia(s)*, insira os dias do mês para as sincronizações ocorrerem. As entradas válidas são *1* até *31* e *Last*. Você pode separar vários dias com uma vírgula ou ponto e vírgula. Use um hífen para datas inclusivas. Por exemplo: 1,3,4,10-15,Last. Você também pode selecionar a caixa de seleção *Select all months* no canto superior direito se quiser um agendamento mensal.




 a| 
Hora de início
 a| 
Na lista suspensa, selecione um novo horário de início para os Snapshots diários. As opções são apresentadas em incrementos de meia hora. O horário de início padrão é meia hora à frente do horário atual.



 a| 
Fuso horário
 a| 
Na lista suspensa, selecione o fuso horário do seu array de storage.



 a| 
Snapshots por dia

Tempo entre Snapshots
 a| 
Selecione o número de imagens de Snapshot a serem criadas por dia.

Se você selecionar mais de um, selecione também o tempo entre os pontos de restauração. Para múltiplos pontos de restauração, certifique-se de ter capacidade reservada adequada.



 a| 
Data de início

Data de término

Sem data de término
 a| 
Insira a data de início para que as sincronizações comecem. Insira também uma data de término ou selecione *Sem data de término*.

|===
====


. Clique em *Salvar*.

