---
permalink: sm-storage/comparison-between-thick-volumes-and-thin-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, comparison, thick volumes, thin volumes 
summary: Um volume espesso é sempre totalmente provisionado, o que significa que toda a capacidade é alocada quando o volume é criado. Um volume fino é sempre com thin provisioning, o que significa que a capacidade é alocada à medida que os dados são gravados no volume. 
---
= Aprenda sobre volumes espessos e finos no software SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um volume espesso é sempre totalmente provisionado, o que significa que toda a capacidade é alocada quando o volume é criado. Um volume fino é sempre com thin provisioning, o que significa que a capacidade é alocada à medida que os dados são gravados no volume.

[NOTE]
====
System Manager não oferece uma opção para criar thin volumes. Se você deseja criar thin volumes, use a command line interface (CLI).

====
[cols="25h,~"]
|===
| Tipo de volume | Descrição 


 a| 
Volumes espessos
 a| 
* Volumes thick são criados a partir de um pool ou grupo de volume.
* Com volumes espessos, uma grande quantidade de espaço de storage é fornecida antecipadamente em antecipação às necessidades futuras de storage.
* Volumes espessos são criados com todo o tamanho do volume pré-alocado no storage físico no momento em que o volume é criado. Essa pré-alocação significa que criar um volume de 100 GiB realmente consome 100 GiB de capacidade alocada em seus discos. No entanto, o espaço pode permanecer não utilizado, causando subutilização da capacidade de storage.
* Ao criar volumes espessos, certifique-se de não alocar capacidade em excesso para um único volume. Alocar capacidade em excesso para um único volume pode consumir rapidamente todo o storage físico do seu sistema.
* Lembre-se de que capacidade de storage também é necessária para serviços de cópia (imagens de Snapshot, volumes de Snapshot, cópias de volume e espelhamento assíncrono), portanto, não aloque toda a capacidade para volumes thick. Espaço insuficiente pode bloquear gravações no pool ou grupo de volume. Você recebe um aviso de limite de capacidade livre se essa situação ocorrer.




 a| 
Volumes com thin provisioning
 a| 
* Volumes com thin provisioning são criados apenas a partir de um pool, não de um grupo de volume.
* Os volumes thin devem ser RAID 6.
* Volumes finos não estão disponíveis nos sistemas de storage EF600/EF600C ou EF300/EF300C.
* Você deve usar a CLI para criar volumes com thin provisioning.
* Ao contrário dos volumes espessos, o espaço necessário para o volume fino não é alocado durante a criação, mas é fornecido sob demanda em um momento posterior.
* Um volume com thin provisioning permite que você superaloque seu tamanho. Ou seja, você pode atribuir um tamanho de LUN maior do que o tamanho do volume. Você pode então expandir o volume conforme necessário (se necessário, adicionando unidades no processo) sem expandir o tamanho do LUN e, portanto, sem desconectar os usuários.
* Você pode usar thin provisioning exigência de espaço (UNMAP) para recuperar blocos de um volume com thin provisioning no array de storage por meio de um comando SCSI UNMAP emitido pelo host. Um array de storage que suporta thin provisioning pode reaproveitar o espaço recuperado para atender solicitações de alocação de outro volume com thin provisioning dentro do mesmo array de storage, o que permite um melhor relatório do consumo de espaço de disco e um uso mais eficiente dos recursos.


|===


== Restrições de thin volume

Volumes com thin provisioning suportam todas as operações que volumes espessos suportam, com as seguintes exceções:

* Não é possível alterar o tamanho do segmento de um volume com thin provisioning.
* Não é possível ativar a verificação de redundância de pré-leitura para um volume com thin provisioning.
* Não é possível usar um volume com thin provisioning como volume de destino em uma operação de Copy Volume.
* Você pode alterar o limite de capacidade alocada e o limite de aviso de um volume com thin provisioning apenas no lado primário de um par espelhado assíncrono. Quaisquer alterações nesses parâmetros no lado primário são propagadas automaticamente para o lado secundário.

