---
permalink: sm-storage/enable-security.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, security, pool, volume group 
summary: Você pode habilitar a Segurança de Unidade para um pool ou grupo de volume para impedir o acesso não autorizado aos dados nas unidades contidas no pool ou grupo de volume. O acesso de leitura e gravação às unidades só está disponível por meio de um controlador configurado com uma chave de segurança. 
---
= Habilite a segurança para um pool ou grupo de volume no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode habilitar a Segurança de Unidade para um pool ou grupo de volume para impedir o acesso não autorizado aos dados nas unidades contidas no pool ou grupo de volume. O acesso de leitura e gravação às unidades só está disponível por meio de um controlador configurado com uma chave de segurança.

.Antes de começar
* O recurso Drive Security deve estar ativado.
* Uma chave de segurança deve ser criada.
* O pool ou grupo de volume deve estar em estado Ótimo.
* Todas as unidades no pool ou grupo de volume devem ser unidades secure-capable.


.Sobre esta tarefa
Se você deseja usar o Drive Security, selecione um pool ou grupo de volume que seja compatível com segurança. Um pool ou grupo de volume pode conter unidades compatíveis com segurança e unidades não compatíveis com segurança, mas todas as unidades devem ser compatíveis com segurança para usar seus recursos de criptografia.

Após ativar a segurança, você só poderá removê-la excluindo o pool ou grupo de volume e, em seguida, apagando as unidades.

.Passos
. Selecione o menu: Storage [Pools & Volume Groups].
. Selecione o pool ou grupo de volume no qual deseja ativar a segurança e clique em menu:More[Enable security].
+
A caixa de diálogo Confirm Enable Security é exibida.

. Confirme que deseja ativar a segurança para o pool ou grupo de volume selecionado e clique em *Ativar*.

