---
permalink: sm-storage/faq-pools-volume-groups.html 
sidebar: sidebar 
keywords:  
summary: Esta FAQ pode ajudar se você estiver apenas procurando uma resposta rápida para uma pergunta. 
---
= Perguntas frequentes sobre pools e grupos de volume para SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta FAQ pode ajudar se você estiver apenas procurando uma resposta rápida para uma pergunta.



== O que é um grupo de volume?

Um grupo de volume é um contêiner para volumes com características compartilhadas. Um grupo de volume tem uma capacidade definida e nível RAID. Você pode usar um grupo de volume para criar um ou mais volumes acessíveis a um host. (Você cria volumes a partir de um grupo de volume ou de um pool.)



== O que é um pool?

Um pool é um conjunto de unidades agrupadas logicamente. Você pode usar um pool para criar um ou mais volumes acessíveis a um host. (Você cria volumes a partir de um pool ou de um grupo de volume.)

Os pools podem eliminar a necessidade de os administradores monitorarem o uso em cada host para determinar quando é provável que fiquem sem espaço de storage e evitar interrupções convencionais para redimensionamento de discos. Quando um pool se aproxima do esgotamento, unidades adicionais podem ser adicionadas ao pool sem interrupção e o crescimento da capacidade é transparente para o host.

Com pools, os dados são redistribuídos automaticamente para manter o equilíbrio. Ao distribuir informações de paridade e capacidade de reserva por todo o pool, cada unidade no pool pode ser usada para reconstruir uma unidade com falha. Essa abordagem não utiliza unidades hot spare dedicadas; em vez disso, a capacidade de preservação (reserva) é reservada em todo o pool. Quando uma unidade falha, os segmentos em outras unidades são lidos para recriar os dados. Uma nova unidade é então escolhida para gravar cada segmento que estava em uma unidade com falha, de modo que a distribuição de dados entre as unidades seja mantida.



== O que é capacidade reservada?

A capacidade reservada é a capacidade fisicamente alocada que armazena dados para objetos do serviço de cópia, como imagens de instantâneo, volumes de membros de grupo de consistência e volumes de pares espelhados.

O volume de capacidade reservada associado a uma operação de serviço de cópia reside em um pool ou um grupo de volume. Você cria capacidade reservada a partir de um pool ou grupo de volume.



== O que é segurança FDE/FIPS?

A segurança FDE/FIPS refere-se a unidades com recursos de segurança que criptografam os dados durante as gravações e descriptografam os dados durante as leituras, utilizando uma chave de criptografia exclusiva. Essas unidades com recursos de segurança impedem o acesso não autorizado aos dados em uma unidade que esteja fisicamente removida do array de storage.

Unidades com recursos de segurança podem ser unidades com criptografia de disco completa (FDE) ou unidades Federal Information Processing Standard (FIPS). Unidades FIPS passaram por testes de certificação.

[NOTE]
====
Para volumes que exigem suporte FIPS, use somente unidades FIPS. Misturar unidades FIPS e FDE em um grupo de volume ou pool fará com que todas as unidades sejam tratadas como unidades FDE. Além disso, uma unidade FDE não pode ser adicionada ou usada como hot spare em um grupo de volume ou pool totalmente FIPS.

====


== O que é verificação de redundância?

Uma verificação de redundância determina se os dados em um volume de um pool ou grupo de volume são consistentes. Os dados de redundância são usados para reconstruir rapidamente as informações em uma unidade de substituição caso uma das unidades do pool ou grupo de volume falhe.

Você só pode executar essa verificação em um pool ou grupo de volume por vez. Uma verificação de redundância de volume executa as seguintes ações:

* Analisa os blocos de dados em um volume RAID 3, um volume RAID 5 ou um volume RAID 6 e, em seguida, verifica as informações de redundância para cada bloco. (RAID 3 só pode ser atribuído a grupos de volume usando a interface de linha de comando.)
* Compara os blocos de dados em unidades RAID 1 espelhadas.
* Retorna erros de redundância se os dados forem considerados inconsistentes pelo firmware do controlador.


[NOTE]
====
Executar imediatamente uma verificação de redundância no mesmo pool ou grupo de volume pode causar um erro. Para evitar esse problema, aguarde de um a dois minutos antes de executar outra verificação de redundância no mesmo pool ou grupo de volume.

====


== Quais são as diferenças entre pools e volume groups?

Um pool é semelhante a um grupo de volume, com as seguintes diferenças.

* Os dados em um pool são armazenados aleatoriamente em todas as unidades do pool, diferentemente dos dados em um grupo de volume, que são armazenados no mesmo conjunto de unidades.
* Um pool apresenta menor degradação de desempenho quando uma unidade falha e leva menos tempo para ser reconstruído.
* Um pool possui capacidade de preservação incorporada; portanto, não requer unidades hot spare dedicadas.
* Um pool permite que um grande número de unidades seja agrupado.
* Um pool não precisa de um nível RAID especificado.




== Por que eu iria querer configurar um pool manualmente?

Os exemplos a seguir descrevem por que você desejaria configurar manualmente um pool.

* Se você tiver vários aplicativos em seu array de storage e não quiser que eles disputem os mesmos recursos de unidade, talvez queira considerar criar manualmente um pool menor para um ou mais dos aplicativos.
+
Você pode atribuir apenas um ou dois volumes em vez de atribuir a carga de trabalho a um pool grande que tem muitos volumes nos quais distribuir os dados. Criar manualmente um pool separado dedicado à carga de trabalho de um aplicativo específico pode permitir que as operações do array de storage sejam executadas mais rapidamente, com menos contenção.

+
Para criar um pool manualmente: selecione *Armazenamento* e, em seguida, selecione *Pools & Volume Groups*. Na guia All Capacity, clique em menu:Create[Pool].

* Se houver vários pools do mesmo tipo de unidade, uma mensagem será exibida indicando que System Manager não pode recomendar as unidades para um pool automaticamente. No entanto, você pode adicionar manualmente as unidades a um pool existente.
+
Para adicionar unidades manualmente a um pool existente: na página Pools & Volume Groups, selecione o pool e clique em *Adicionar Capacidade*.





== Por que os alertas de capacidade são importantes?

Os alertas de capacidade indicam quando adicionar unidades a um pool. Um pool precisa de capacidade livre suficiente para executar com sucesso as operações do array de storage. Você pode evitar interrupções nessas operações configurando o SANtricity System Manager para enviar alertas quando a capacidade livre de um pool atingir ou exceder uma porcentagem especificada.

Você define essa porcentagem ao criar um pool usando a opção *Configuração automática do pool* ou a opção *Criar pool*. Se escolher a opção automática, as configurações padrão determinam automaticamente quando você recebe notificações de alerta. Se optar por criar o pool manualmente, você pode definir as configurações de notificação de alerta; ou, se preferir, pode aceitar as configurações padrão. Você pode ajustar essas configurações depois em menu:Configurações[Alertas].

[NOTE]
====
Quando a capacidade livre no pool atinge a porcentagem especificada, uma notificação de alerta é enviada usando o método que você especificou na configuração de alerta.

====


== Por que não posso aumentar minha capacidade de preservação?

Se você já criou volumes em toda a capacidade utilizável disponível, talvez não seja possível aumentar a capacidade de preservação.

A capacidade de preservação é a quantidade de capacidade (número de unidades) reservada em um pool para suportar possíveis falhas de unidades. Quando um pool é criado, o sistema reserva automaticamente uma quantidade padrão de capacidade de preservação dependendo do número de unidades no pool. Se você criou volumes em toda a capacidade utilizável disponível, não poderá aumentar a capacidade de preservação sem adicionar capacidade ao pool, seja adicionando unidades ou excluindo volumes.

Você pode alterar a capacidade de preservação em *Pools & Volume Groups*. Selecione o pool que você deseja editar. Clique em *View/Edit Settings* e, em seguida, selecione a guia *Settings*.

[NOTE]
====
A capacidade de preservação é especificada como um número de unidades, mesmo que a capacidade real de preservação seja distribuída entre as unidades no pool.

====


== Existe um limite para o número de unidades que posso remover de um pool?

SANtricity System Manager define limites para quantas unidades você pode remover de um pool.

* Não é possível reduzir o número de unidades em um pool para menos de 11 unidades.
* Não é possível remover unidades se não houver capacidade livre suficiente no pool para conter os dados das unidades removidas quando esses dados forem redistribuídos para as unidades restantes no pool.
* Você pode remover no máximo 60 unidades por vez. Se você selecionar mais de 60 unidades, a opção Remover Unidades será desativada. Se precisar remover mais de 60 unidades, repita a operação Remover Unidades.




== Quais tipos de mídia são suportados para uma unidade?

Os seguintes tipos de mídia são suportados: Hard Disk Drive (HDD) e Solid State Disk (SSD).



== Por que algumas unidades não estão aparecendo?

Na caixa de diálogo Adicionar Capacidade, nem todas as unidades estão disponíveis para adicionar capacidade a um pool ou grupo de volume.

As unidades não são elegíveis por nenhum dos seguintes motivos:

* A unidade deve estar desatribuída e não habilitada para segurança. Unidades que já fazem parte de outro pool, outro grupo de volume ou que estejam configuradas como hot spare não são elegíveis. Se uma unidade estiver desatribuída, mas estiver habilitada para segurança, você deverá apagá-la manualmente para que se torne elegível.
* Uma unidade que está em um estado não ideal não é elegível.
* Se a capacidade de uma unidade for muito pequena, ela não será elegível.
* O tipo de mídia da unidade deve corresponder dentro de um pool ou grupo de volume. Você não pode misturar o seguinte:
+
** Unidades de disco rígido (HDDs) com Solid State Disks (SSDs)
** NVMe com unidades SAS
** Unidades com tamanhos de bloco de volume de 512 bytes e 4KiB


* Se um pool ou grupo de volume contiver apenas unidades com capacidade de segurança, as unidades sem capacidade de segurança não serão listadas.
* Se um pool ou grupo de volume contiver todas as unidades Federal Information Processing Standards (FIPS), as unidades não FIPS não serão listadas.
* Se um pool ou grupo de volume contiver todas as unidades compatíveis com Data Assurance (DA) e houver pelo menos um volume com DA habilitado nesse pool ou grupo de volume, uma unidade que não seja compatível com DA não será elegível, portanto, não poderá ser adicionada a esse pool ou grupo de volume. No entanto, se não houver nenhum volume com DA habilitado no pool ou grupo de volume, uma unidade que não seja compatível com DA pode ser adicionada a esse pool ou grupo de volume. Se você decidir misturar essas unidades, lembre-se de que não poderá criar nenhum volume com DA habilitado.


[NOTE]
====
A capacidade pode ser aumentada no seu array de storage adicionando novas unidades ou excluindo pools ou grupos de volumes.

====


== Como faço para manter a proteção contra perda de prateleira/gaveta?

Para manter a proteção contra perdas em prateleiras/gavetas para um pool ou grupo de volume, utilize os critérios especificados na tabela a seguir.

[cols="1a,1a,1a"]
|===
| Nível | Critérios para proteção contra perda de prateleira/gaveta | Número mínimo de prateleiras/gavetas necessárias 


 a| 
Pool
 a| 
Para prateleiras, o pool não deve conter mais de duas unidades em uma única prateleira.

Para gavetas, o pool deve incluir um número igual de unidades de cada gaveta.
 a| 
6 para prateleiras

5 para gavetas



 a| 
RAID 6
 a| 
O grupo de volume contém no máximo duas unidades em uma única shelf ou drawer.
 a| 
3



 a| 
RAID 3 ou RAID 5
 a| 
Cada unidade no grupo de volume está localizada em uma prateleira ou gaveta separada.
 a| 
3



 a| 
RAID 1
 a| 
Cada unidade em um par espelhado deve estar localizada em uma prateleira ou gaveta separada.
 a| 
2



 a| 
RAID 0
 a| 
Não é possível obter proteção contra perda de shelf/drawer.
 a| 
Não aplicável

|===
[NOTE]
====
A proteção contra perda de shelf/gaveta não é mantida se uma unidade já tiver falhado no pool ou grupo de volume. Nessa situação, a perda de acesso a um shelf ou gaveta de unidade e, consequentemente, a outra unidade no pool ou grupo de volume, causa perda de dados.

====


== Qual é o posicionamento ideal das unidades para pools e grupos de volume?

Ao criar pools e grupos de volume, certifique-se de equilibrar a seleção de unidades entre os slots de unidade superiores e inferiores.

Nos controladores EF600 e EF300, os slots de unidade 0 a 11 estão conectados a uma ponte PCI, enquanto os slots 12 a 23 estão conectados a outra ponte PCI. Para desempenho ideal, você deve equilibrar a seleção das unidades para incluir um número aproximadamente igual de unidades nos slots superiores e inferiores. Esse posicionamento garante que seus volumes não atinjam um limite de largura de banda antes do necessário.



== Qual nível RAID é o melhor para minha aplicação?

Para maximizar o desempenho de um grupo de volume, você deve selecionar o nível RAID apropriado. Você pode determinar o nível RAID apropriado conhecendo as porcentagens de leitura e gravação dos aplicativos que acessam o grupo de volume. Use a página Desempenho para obter essas porcentagens.



=== Níveis RAID e desempenho do aplicativo

RAID utiliza uma série de configurações, chamadas de _níveis_, para determinar como os dados do usuário e os dados de redundância são gravados e recuperados das unidades. Cada nível RAID oferece diferentes recursos de desempenho. Aplicativos com alta porcentagem de leitura terão um bom desempenho usando volumes RAID 5 ou volumes RAID 6 devido ao excelente desempenho de leitura das configurações RAID 5 e RAID 6.

Aplicações com baixa porcentagem de leitura (uso intensivo de escrita) não apresentam o mesmo desempenho em volumes RAID 5 ou volumes RAID 6. A degradação de desempenho resulta da forma como o controlador grava dados e dados de redundância nas unidades em um grupo de volume RAID 5 ou um grupo de volume RAID 6.

Selecione um nível RAID com base nas seguintes informações.

*RAID 0*

* *Descrição*
+
** Não redundante, modo de striping.


* *Como funciona*
+
** RAID 0 distribui os dados por todas as unidades do grupo de volume.


* *Recursos de proteção de dados*
+
** RAID 0 não é recomendado para necessidades de alta disponibilidade. RAID 0 é mais adequado para dados não críticos.
** Se uma unidade única falhar no grupo de volume, todos os volumes associados falham e todos os dados são perdidos.


* *Requisitos de número de unidades*
+
** É necessário no mínimo um disco rígido para o nível RAID 0.
** Grupos de volume RAID 0 podem ter mais de 30 unidades.
** Você pode criar um grupo de volume que inclua todas as unidades no storage array.




*RAID 1 ou RAID 10*

* *Descrição*
+
** Modo striping/espelhamento.


* *Como funciona*
+
** RAID 1 utiliza espelhamento de disco para gravar dados em dois discos duplicados simultaneamente.
** RAID 10 usa o striping de unidades para distribuir os dados entre um conjunto de pares de unidades espelhadas.


* *Recursos de proteção de dados*
+
** RAID 1 e RAID 10 oferecem alto desempenho e a melhor disponibilidade de dados.
** RAID 1 e RAID 10 usam o espelhamento de unidade para fazer uma cópia exata de uma unidade para outra unidade.
** Se uma das unidades em um par de unidades falhar, o array de storage pode alternar instantaneamente para a outra unidade sem qualquer perda de dados ou serviço.
** A falha de uma unidade única faz com que os volumes associados fiquem degradados. A unidade espelhada permite o acesso aos dados.
** A falha de um par de unidades em um grupo de volume causa a falha de todos os volumes associados, e pode ocorrer perda de dados.


* *Requisitos de número de unidades*
+
** É necessário um mínimo de duas unidades para RAID 1: uma unidade para os dados de usuário e uma unidade para os dados espelhados.
** Se você selecionar quatro ou mais unidades, RAID 10 é configurado automaticamente em todo o grupo de volume: duas unidades para dados de usuário e duas unidades para os dados espelhados.
** Você precisa ter um número par de unidades no grupo de volume. Se você não tiver um número par de unidades e ainda tiver algumas unidades não atribuídas, acesse *Pools & Volume Groups* para adicionar unidades adicionais ao grupo de volume e tente a operação novamente.
** Os grupos de volume RAID 1 e RAID 10 podem ter mais de 30 unidades. Um grupo de volume pode ser criado que inclua todas as unidades no array de storage.




*RAID 5*

* *Descrição*
+
** Modo de alta E/S.


* *Como funciona*
+
** Os dados de usuário e as informações redundantes (paridade) são distribuídos entre os discos.
** A capacidade equivalente de uma unidade é usada para informações redundantes.


* *Recursos de proteção de dados*
+
** Se uma unidade única falhar em um grupo de volume RAID 5, todos os volumes associados ficarão degradados. As informações redundantes permitem que os dados ainda possam ser acessados.
** Se duas ou mais unidades falharem em um grupo de volume RAID 5, todos os volumes associados falharão e todos os dados serão perdidos.


* *Requisitos de número de unidades*
+
** Você deve ter no mínimo três unidades no grupo de volume.
** Normalmente, você está limitado a um máximo de 30 drives no grupo de volume.




*RAID 6*

* *Descrição*
+
** Modo de alta E/S.


* *Como funciona*
+
** Os dados de usuário e as informações redundantes (paridade dupla) são distribuídos entre as unidades.
** A capacidade equivalente de duas unidades é usada para informações redundantes.


* *Recursos de proteção de dados*
+
** Se uma ou duas unidades falharem em um grupo de volume RAID 6, todos os volumes associados ficam degradados, mas as informações redundantes permitem que os dados ainda sejam acessados.
** Se três ou mais unidades falharem em um grupo de volume RAID 6, todos os volumes associados falharão e todos os dados serão perdidos.


* *Requisitos de número de unidades*
+
** Você deve ter no mínimo cinco drives no grupo de volume.
** Normalmente, você está limitado a um máximo de 30 drives no grupo de volume.




[NOTE]
====
Não é possível alterar o nível RAID de um pool. A interface de usuário configura automaticamente os pools como RAID 6.

====


=== Níveis RAID e proteção de dados

RAID 1, RAID 5 e RAID 6 gravam dados de redundância na mídia do disco para tolerância de falhas. Os dados de redundância podem ser uma cópia dos dados (espelhados) ou um código de correção de erros derivado dos dados. Você pode usar os dados de redundância para reconstruir rapidamente as informações em um disco de substituição caso um disco falhe.

Você configura um único nível RAID em um único grupo de volume. Todos os dados de redundância para esse grupo de volume são armazenados dentro do grupo de volume. A capacidade do grupo de volume é a capacidade agregada das unidades membros menos a capacidade reservada para dados de redundância. A quantidade de capacidade necessária para redundância depende do nível RAID utilizado.



== O que é Data Assurance?

A Garantia de Dados (DA) implementa o padrão T10 Protection Information (PI), que aumenta a integridade de dados ao verificar e corrigir erros que possam ocorrer durante a transferência de dados ao longo do caminho de E/S.

O uso típico do recurso Data Assurance consiste em verificar a porção do caminho de E/S entre os controladores e as unidades. Os recursos de DA são apresentados nos níveis de pool e grupo de volume.

Quando esse recurso está habilitado, o array de storage anexa códigos de verificação de erros (também conhecidos como verificações de redundância cíclica ou CRCs) a cada bloco de dados no volume. Após a movimentação de um bloco de dados, o array de storage usa esses códigos CRC para determinar se ocorreram erros durante a transmissão. Dados potencialmente corrompidos não são gravados em disco nem retornados ao host. Se você deseja usar o recurso DA, selecione um pool ou grupo de volume compatível com DA ao criar um novo volume (procure por "Sim" ao lado de "DA" na tabela de candidatos de pool e grupo de volumes).

Certifique-se de atribuir esses volumes habilitados para DA a um host usando uma interface de E/S compatível com DA. Interfaces de E/S compatíveis com DA incluem Fibre Channel, SAS, iSCSI sobre TCP/IP, NVMe/FC, NVMe/IB, NVMe/RoCE e iSER sobre InfiniBand (iSCSI Extensions for RDMA/IB). DA não é compatível com SRP sobre InfiniBand.



== O que é secure-capable (Drive Security)?

A Segurança de Unidade é um recurso que impede o acesso não autorizado a dados em unidades com segurança habilitada quando removidas do array de storage. Essas unidades podem ser unidades Full Disk Encryption (FDE) ou unidades Federal Information Processing Standard (FIPS).



== O que preciso saber sobre o aumento da capacidade reservada?

Normalmente, você deve aumentar a capacidade quando receber um aviso de que a capacidade reservada está prestes a ficar cheia. Você só pode aumentar a capacidade reservada apenas em incrementos de 8 GiB.

* Você deve ter capacidade livre suficiente no pool ou grupo de volume para que ele possa ser expandido se necessário.
+
Se não houver capacidade livre em nenhum pool ou grupo de volume, você pode adicionar capacidade não atribuída na forma de drives não utilizados a um pool ou grupo de volume.

* O volume no pool ou grupo de volume deve ter um status Ótimo e não deve estar em nenhum estado de modificação.
* Deve haver capacidade livre no pool ou volume group que você deseja usar para aumentar a capacidade.
* Não é possível aumentar a capacidade reservada para um volume de snapshot que seja somente leitura. Apenas volumes de snapshot que sejam de leitura e gravação requerem capacidade reservada.


Para operações de snapshot, a capacidade reservada normalmente corresponde a 40% do volume base. Para operações de espelhamento assíncrono, a capacidade reservada normalmente corresponde a 20% do volume base. Use uma porcentagem maior se você acredita que o volume base sofrerá muitas alterações ou se a expectativa de vida útil da operação de serviço de cópia de um objeto de storage for muito longa.



== Por que não posso escolher outro valor para diminuir?

Você só pode diminuir a capacidade reservada na mesma proporção em que a aumentou. A capacidade reservada para volumes de membros só pode ser removida na ordem inversa em que foram adicionados.

Não é possível diminuir a capacidade reservada para um objeto de storage se uma destas condições existir:

* Se o objeto de armazenamento for um volume de par espelhado.
* Se o objeto de armazenamento contiver apenas um volume para capacidade reservada. O objeto de armazenamento deve conter pelo menos dois volumes para capacidade reservada.
* Se o objeto de armazenamento for um volume de snapshot desativado.
* Se o objeto de armazenamento contiver uma ou mais imagens de snapshot associadas.


Você pode remover volumes para capacidade reservada somente na ordem inversa em que foram adicionados.

Não é possível diminuir a capacidade reservada para um volume de snapshot que seja somente leitura porque ele não possui nenhuma capacidade reservada associada. Somente volumes de snapshot que sejam de leitura e gravação requerem capacidade reservada.



== Por que preciso de capacidade reservada para cada volume de membro?

Cada volume membro em um grupo de consistência de snapshot deve ter sua própria capacidade reservada para salvar quaisquer modificações feitas pelo aplicativo host no volume base, sem afetar a imagem de snapshot do grupo de consistência referenciada. A capacidade reservada fornece ao aplicativo host acesso de gravação a uma cópia dos dados contidos no volume membro designado como leitura/gravação.

Uma imagem de snapshot de grupo de consistência não é diretamente acessível para leitura ou gravação pelos hosts. Em vez disso, a imagem de snapshot é usada para salvar apenas os dados capturados do volume base.

Durante a criação de um volume de snapshot de grupo de consistência designado como leitura e gravação, o System Manager cria uma capacidade reservada para cada volume membro no grupo de consistência. Essa capacidade reservada fornece ao aplicativo host acesso de gravação a uma cópia dos dados contidos na imagem de snapshot do grupo de consistência.



== Como faço para visualizar e interpretar todas as estatísticas do SSD Cache?

Você pode visualizar estatísticas nominais e estatísticas detalhadas para o cache SSD. As estatísticas nominais são um subconjunto das estatísticas detalhadas.

As estatísticas detalhadas só podem ser visualizadas ao exportar todas as estatísticas de SSD para um  `.csv` arquivo. Ao analisar e interpretar as estatísticas, lembre-se de que algumas interpretações são derivadas da análise de uma combinação de estatísticas.



=== Estatísticas nominais

Para visualizar as estatísticas do SSD Cache, selecione menu:Storage[Pools & Volume Groups]. Selecione o SSD Cache para o qual deseja visualizar as estatísticas e, em seguida, selecione menu:More[View Statistics]. As estatísticas nominais são exibidas na caixa de diálogo Exibir Estatísticas do SSD Cache.

A lista a seguir inclui estatísticas nominais, que são um subconjunto das estatísticas detalhadas.

[cols="25h,~"]
|===
| Estatística nominal | Descrição 


 a| 
Leituras/Gravações
 a| 
O número total de leituras do host ou gravações do host nos volumes com SSD Cache ativado. Compare as leituras em relação às gravações. As leituras precisam ser maiores que as gravações para uma operação eficaz do SSD Cache. Quanto maior a proporção de leituras para gravações, melhor a operação do cache.



 a| 
Acertos do cache
 a| 
Uma contagem do número de acertos do cache.



 a| 
Acertos do cache (%)
 a| 
Derivado de acerto do cache / (leituras + gravações). A porcentagem de acerto do cache deve ser superior a 50 por cento para uma operação eficaz do cache SSD. Um número baixo pode indicar várias coisas:

* A proporção de leituras para gravações é muito baixa
* As leituras não são repetidas
* A capacidade do cache é muito pequena




 a| 
Alocação de cache (%)
 a| 
A quantidade de armazenamento de cache SSD que está alocada, expressa como uma porcentagem do armazenamento de cache SSD que está disponível para este controlador. Derivada de bytes alocados / bytes disponíveis. A porcentagem de alocação de cache normalmente é exibida como 100 por cento. Se esse número for menor que 100 por cento, significa que o cache não foi aquecido ou que a capacidade do cache SSD é maior do que todos os dados acessados. No último caso, uma capacidade menor de cache SSD pode fornecer o mesmo nível de desempenho. Observe que isso não indica que os dados em cache foram colocados no cache SSD; é simplesmente uma etapa de preparação antes que os dados possam ser colocados no cache SSD.



 a| 
Utilização do cache (%)
 a| 
A quantidade de armazenamento SSD Cache que contém dados de volumes habilitados, expressa como uma porcentagem do armazenamento SSD Cache que está alocado. Esse valor representa a utilização ou densidade do SSD Cache derivada da proporção de bytes de dados de usuário / bytes alocados. A porcentagem de utilização do cache normalmente é inferior a 100 por cento, podendo ser bem menor. Esse número mostra a porcentagem da capacidade do SSD Cache que está preenchida com dados de cache. Esse número é inferior a 100 por cento porque cada unidade de alocação do SSD Cache, o bloco do SSD Cache, é dividida em unidades menores chamadas sub-blocos, que são preenchidas de forma relativamente independente. Um número maior geralmente é melhor, mas os ganhos de desempenho podem ser significativos mesmo com um número menor.

|===


=== Estatísticas detalhadas

As estatísticas detalhadas consistem nas estatísticas nominais, além de estatísticas adicionais. Essas estatísticas adicionais são salvas juntamente com as estatísticas nominais, mas, diferentemente das estatísticas nominais, não são exibidas na caixa de diálogo Exibir Estatísticas do Cache SSD. Você pode visualizar as estatísticas detalhadas somente após exportar as estatísticas para um arquivo  `.csv`.

Ao visualizar o  `.csv`arquivo, observe que as estatísticas detalhadas são listadas após as estatísticas nominais:

[cols="25h,~"]
|===
| Estatísticas detalhadas | Descrição 


 a| 
Blocos de leitura
 a| 
O número de blocos em leituras do host.



 a| 
Blocos de escrita
 a| 
O número de blocos em gravações do host.



 a| 
Blocos de acerto total
 a| 
O número de blocos em acertos do cache. Os blocos de acerto completo indicam o número de blocos que foram lidos inteiramente do SSD Cache. O SSD Cache só é benéfico para o desempenho para aquelas operações que são acertos completos do cache.



 a| 
Acertos parciais
 a| 
O número de leituras do host em que pelo menos um bloco, mas não todos os blocos, estavam no SSD Cache. Um acerto parcial é um *miss* no SSD Cache, onde as leituras foram atendidas a partir do volume base.



 a| 
Acertos Parciais - Blocos
 a| 
O número de blocos em acertos parciais. Acertos parciais do cache e blocos de acerto parcial do cache resultam de uma operação que possui apenas uma parte de seus dados no SSD Cache. Nesse caso, a operação precisa obter os dados do volume do disco rígido (HDD) em cache. O SSD Cache não oferece nenhum benefício de desempenho para esse tipo de acerto. Se a contagem de blocos de acerto parcial do cache for maior que a de blocos de acerto completo do cache, um tipo diferente de característica de E/S (sistema de arquivos, banco de dados ou servidor web) poderia melhorar o desempenho. Espera-se que haja um número maior de acertos e falhas parciais em comparação com acertos de cache enquanto o SSD Cache estiver aquecendo.



 a| 
Perdas
 a| 
O número de leituras do host em que nenhum dos blocos estava no SSD Cache. Uma falha de SSD Cache ocorre quando as leituras foram atendidas a partir do volume base. Espera-se que haja um número maior de acertos e falhas parciais em comparação com os acertos do cache enquanto o SSD Cache estiver aquecendo.



 a| 
Perdas - Blocos
 a| 
O número de blocos em Misses.



 a| 
Ações de preenchimento (leituras do host)
 a| 
O número de leituras do host em que os dados foram copiados do volume base para o SSD Cache.



 a| 
Preencher ações (leituras do host) - blocos
 a| 
O número de blocos em Populate Actions (Host Reads).



 a| 
Ações de preenchimento (escritas do host)
 a| 
O número de gravações do host em que os dados foram copiados do volume base para o SSD Cache. A contagem de Populate Actions (Host Writes) pode ser zero para as configurações de cache que não preenchem o cache como resultado de uma operação de gravação de E/S.



 a| 
Ações de preenchimento (Host Writes) - Blocos
 a| 
O número de blocos em Populate Actions (Host Writes).



 a| 
Invalidar ações
 a| 
Número de vezes que os dados foram invalidados ou removidos do SSD Cache. Uma operação de invalidação de cache é realizada para cada solicitação de gravação do host, cada solicitação de leitura do host com Forced Unit Access (FUA), cada solicitação de verificação e em algumas outras circunstâncias.



 a| 
Ações de reciclagem
 a| 
O número de vezes que o bloco de cache SSD foi reutilizado para outro volume base e/ou um intervalo de endereçamento de bloco lógico (LBA) diferente. Para uma operação de cache eficaz, o número de reciclagens deve ser pequeno em comparação com o número combinado de operações de leitura e gravação. Se o número de ações de reciclagem for próximo ao número combinado de leituras e gravações, o SSD Cache está apresentando thrashing. A capacidade do cache precisa ser aumentada ou a carga de trabalho não é adequada para uso com SSD Cache.



 a| 
Bytes disponíveis
 a| 
O número de bytes disponíveis no SSD Cache para uso por este controlador.



 a| 
Bytes alocados
 a| 
O número de bytes alocados do SSD Cache por este controlador. Os bytes alocados do SSD Cache podem estar vazios ou podem conter dados de volumes base.



 a| 
Bytes de dados de usuário
 a| 
O número de bytes alocados no cache SSD que contêm dados dos volumes base. Os bytes disponíveis, os bytes alocados e os bytes de dados de usuário são usados para calcular a porcentagem de alocação de cache e a porcentagem de utilização de cache.

|===


== O que é capacidade de otimização para pools?

Unidades SSD terão vida útil mais longa e melhor desempenho máximo de gravação quando uma parte de sua capacidade estiver não alocada.

Para unidades associadas a um pool, a capacidade não alocada é composta pela capacidade de preservação do pool, a capacidade livre (capacidade não utilizada pelos volumes) e uma porção da capacidade utilizável reservada como capacidade de otimização adicional. A capacidade de otimização adicional garante um nível mínimo de capacidade de otimização ao reduzir a capacidade utilizável e, assim, não está disponível para criação de volumes.

Ao criar um pool, é gerada uma capacidade de otimização recomendada que proporciona um equilíbrio entre desempenho, vida útil da unidade e capacidade disponível. O controle deslizante Capacidade de Otimização Adicional, localizado na caixa de diálogo Configurações do Pool, permite ajustes na capacidade de otimização do pool. Ajustar o controle deslizante proporciona melhor desempenho e vida útil da unidade à custa da capacidade disponível, ou capacidade disponível adicional à custa do desempenho e da vida útil da unidade.

[NOTE]
====
O controle deslizante de Capacidade de Otimização Adicional está disponível apenas para os sistemas de storage EF600 e EF300.

====


== Qual é a capacidade de otimização para grupos de volume?

Unidades SSD terão vida útil mais longa e melhor desempenho máximo de gravação quando uma parte de sua capacidade estiver não alocada.

Para unidades associadas a um grupo de volume, a capacidade não alocada é composta pela capacidade livre do grupo de volume (capacidade não utilizada pelos volumes) e por uma porção da capacidade utilizável reservada como capacidade de otimização. A capacidade de otimização adicional garante um nível mínimo de capacidade de otimização ao reduzir a capacidade utilizável e, assim, não está disponível para criação de volumes.

Quando um grupo de volume é criado, uma capacidade de otimização recomendada é gerada que oferece um equilíbrio entre desempenho, vida útil do disco e capacidade disponível. O controle deslizante Capacidade de Otimização Adicional na caixa de diálogo Configurações do Grupo de Volume permite ajustes na capacidade de otimização de um grupo de volume. Ajustar o controle deslizante proporciona melhor desempenho e vida útil do disco à custa da capacidade disponível, ou capacidade disponível adicional à custa do desempenho e da vida útil do disco.

[NOTE]
====
O controle deslizante de Capacidade de Otimização Adicional está disponível apenas para os sistemas de storage EF600 e EF300.

====


== O que o provisionamento de recursos é capaz de fazer?

O Resource Provisioning é um recurso disponível nos sistemas de storage EF300 e EF600, que permite que os volumes sejam colocados em uso imediatamente, sem processo de inicialização em segundo plano.

Um volume com recursos provisionados é um volume espesso em um grupo de volume SSD ou pool, onde a capacidade do disco é alocada (atribuída ao volume) quando o volume é criado, mas os blocos do disco são desalocados (desmapeados). Em comparação, em um volume espesso tradicional, todos os blocos do disco são mapeados ou alocados durante uma operação de inicialização do volume em segundo plano para inicializar os campos de informações de proteção do Data Assurance e tornar os dados e a paridade RAID consistentes em cada faixa RAID. Com um volume com recursos provisionados, não há inicialização em segundo plano com limite de tempo. Em vez disso, cada faixa RAID é inicializada na primeira gravação em um bloco de volume na faixa.

Volumes provisionados por recurso são suportados apenas em grupos de volumes SSD e pools, onde todas as unidades no grupo ou pool suportam a capacidade de recuperação de erros NVMe Deallocated or Unwritten Logical Block Error Enable (DULBE). Quando um volume provisionado por recurso é criado, todos os blocos de unidade atribuídos ao volume são desalocados (desmapeados). Além disso, hosts podem desalocar blocos lógicos no volume usando o comando NVMe Dataset Management ou o comando SCSI Unmap. Desalocar blocos pode melhorar a vida útil do SSD e aumentar o desempenho máximo de gravação. A melhoria varia com cada modelo de unidade e capacidade.


NOTE: DULBE não é suportado nos arrays de storage EF300C ou EF600C neste momento.



== O que preciso saber sobre o recurso de volumes provisionados por recurso?

O Resource Provisioning é um recurso disponível nos sistemas de storage EF300 e EF600, que permite que os volumes sejam colocados em uso imediatamente, sem processo de inicialização em segundo plano.

Um volume com recursos provisionados é um volume espesso em um grupo de volume SSD ou pool, onde a capacidade do disco é alocada (atribuída ao volume) quando o volume é criado, mas os blocos do disco são desalocados (desmapeados). Em comparação, em um volume espesso tradicional, todos os blocos do disco são mapeados ou alocados durante uma operação de inicialização do volume em segundo plano para inicializar os campos de informações de proteção do Data Assurance e tornar os dados e a paridade RAID consistentes em cada faixa RAID. Com um volume com recursos provisionados, não há inicialização em segundo plano com limite de tempo. Em vez disso, cada faixa RAID é inicializada na primeira gravação em um bloco de volume na faixa.

Volumes provisionados por recurso são suportados apenas em grupos de volumes SSD e pools, onde todas as unidades no grupo ou pool suportam a capacidade de recuperação de erros NVMe Deallocated or Unwritten Logical Block Error Enable (DULBE). Quando um volume provisionado por recurso é criado, todos os blocos de unidade atribuídos ao volume são desalocados (desmapeados). Além disso, hosts podem desalocar blocos lógicos no volume usando o comando NVMe Dataset Management ou o comando SCSI Unmap. Desalocar blocos pode melhorar a vida útil do SSD e aumentar o desempenho máximo de gravação. A melhoria varia com cada modelo de unidade e capacidade.

O provisionamento de recursos está ativado por padrão em sistemas onde as unidades suportam DULBE. Você pode desativar essa configuração padrão em *Pools & Grupos de Volume*.


NOTE: DULBE não é suportado nos arrays de storage EF300C ou EF600C neste momento.
