---
permalink: sm-storage/how-volumes-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, copy, 
summary: Os volumes são contêineres de dados que gerenciam e organizam o espaço de storage no seu array de storage. 
---
= Como funcionam os volumes no SANtricity software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os volumes são contêineres de dados que gerenciam e organizam o espaço de storage no seu array de storage.

Você cria volumes a partir da capacidade de storage disponível em seu array de storage e facilita a organização e o uso dos recursos do seu sistema. Esse conceito é semelhante ao uso de pastas/diretórios em um computador para organizar arquivos para acesso fácil e rápido.

Os volumes são a única camada de dados visível para os hosts. Em um ambiente SAN, os volumes são mapeados para números de unidades lógicas (LUNs), que são visíveis para os hosts. Os LUNs armazenam os dados de usuário que são acessíveis usando um ou mais dos protocolos de acesso do host suportados pelo array de storage, incluindo FC, iSCSI e SAS.



== Tipos de volume que você pode criar a partir de pools e grupos de volume

Os volumes obtêm sua capacidade de pools ou grupos de volume. Você pode criar os seguintes tipos de volumes a partir dos pools ou grupos de volume existentes em seu array de storage.

* *A partir de pools* -- Você pode criar volumes a partir de um pool como _volumes totalmente provisionados (thick)_ ou _volumes com thin provisioning (thin)._
+
[NOTE]
====
A interface do System Manager não oferece uma opção para criar volumes thin. Se você deseja criar volumes thin, use a Command Line Interface (CLI).

====
* *A partir de grupos de volume* -- Você pode criar volumes a partir de um grupo de volume somente como _volumes totalmente provisionados (espessos)_.


Volumes espessos e volumes finos consomem capacidade do array de storage de maneiras diferentes:

* A capacidade para um volume thick é alocada quando o volume é criado.
* A capacidade de um volume fino é alocada como dados quando gravados no volume.


O thin provisioning ajuda a evitar o desperdício de capacidade alocada e pode economizar custos iniciais de storage para as empresas. No entanto, o full provisioning tem a vantagem de menor latência, pois todo o storage é alocado de uma só vez quando thick volumes são criados.

[NOTE]
====
Os sistemas de storage EF600/EF600C e EF300/EF300C não suportam thin provisioning.

====


== Características dos volumes

Cada volume em um pool ou grupo de volume pode ter suas próprias características individuais com base no tipo de dados que serão armazenados nele. Algumas dessas características incluem:

* *Tamanho do segmento* -- Um segmento é a quantidade de dados em kilobytes (KiB) armazenada em uma unidade antes que o array de storage passe para a próxima unidade na faixa (grupo RAID). O tamanho do segmento é igual ou menor que a capacidade do grupo de volume. O tamanho do segmento é fixo e não pode ser alterado para pools.
* *Capacidade* -- Você cria um volume a partir da capacidade livre disponível em um pool ou grupo de volume. Antes de criar um volume, o pool ou grupo de volume já deve existir e deve ter capacidade livre suficiente para criar o volume.
* *Propriedade do controlador* -- Todos os arrays de storage podem ter um ou dois controladores. Em um array com um único controlador, a carga de trabalho de um volume é gerenciada por um único controlador. Em um array com controladora dupla, um volume terá um controlador preferencial (A ou B) que "possui" o volume. Em uma configuração com controladora dupla, a propriedade do volume é ajustada automaticamente usando o recurso de Automatic Load Balancing para corrigir quaisquer problemas de balanceamento de carga quando as cargas de trabalho são transferidas entre os controladores. O Automatic Load Balancing fornece balanceamento automático da carga de E/S e garante que o tráfego de E/S de entrada dos hosts seja gerenciado e balanceado dinamicamente entre os dois controladores.
* *Atribuição de volume* -- Você pode conceder acesso a um volume a hosts, seja no momento da criação do volume ou posteriormente. Todo o acesso dos hosts é gerenciado por meio de um número de unidade lógica (LUN). Os hosts detectam os LUNs que, por sua vez, são atribuídos aos volumes. Se você estiver atribuindo um volume a vários hosts, use clustering para garantir que o volume esteja disponível para todos os hosts.
+
O tipo de host pode ter limites específicos quanto ao número de volumes que o host pode acessar. Leve essa limitação em consideração ao criar volumes para uso por um host específico.

* *Nome descritivo* -- Você pode nomear um volume como quiser, mas recomendamos que o nome seja descritivo.


Durante a criação de um volume, a cada volume é alocada capacidade e são atribuídos um nome, tamanho de segmento (apenas para grupos de volume), propriedade do controlador e atribuição de volume ao host. Os dados do volume são automaticamente balanceados entre os controladores, conforme necessário.
