---
permalink: sm-storage/increase-capacity-of-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, increase, capacity, volume 
summary: 'Você pode aumentar a capacidade relatada (a capacidade relatada aos hosts) de um volume usando a capacidade livre disponível no pool ou volume group.' 
---
= Aumentar a capacidade de um volume no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode aumentar a capacidade relatada (a capacidade relatada aos hosts) de um volume usando a capacidade livre disponível no pool ou volume group.

.Antes de começar
* Existe capacidade livre suficiente disponível no pool ou grupo de volume associado do volume.
* O volume está ótimo e não se encontra em nenhum estado de modificação.
* A capacidade máxima relatada de 256 TiB não foi atingida para thin volumes.
* Não há hot spare em uso no volume. (Aplica-se somente a volumes em grupos de volumes.)



NOTE: Você só pode expandir a capacidade de volume até 128 TiB de cada vez.

.Sobre esta tarefa
Leve em consideração quaisquer requisitos futuros de capacidade que você possa ter para outros volumes neste pool ou grupo de volume. Certifique-se de reservar capacidade livre suficiente para criar imagens de snapshot, volumes de snapshot ou espelhos remotos.

[NOTE]
====
Aumentar a capacidade de um volume só é compatível com determinados sistemas operacionais. Se você aumentar a capacidade do volume em um sistema operacional que não seja compatível, a capacidade expandida ficará inutilizável e você não poderá restaurar a capacidade original do volume.

====
.Passos
. Selecione o menu: storage [Volumes].
. Selecione o volume para o qual deseja aumentar a capacidade e, em seguida, selecione *Increase Capacity*.
+
A caixa de diálogo Confirm Increase Capacity é exibida.

. Selecione *Yes* para continuar.
+
A caixa de diálogo Aumentar a capacidade relatada é exibida.

+
Esta caixa de diálogo exibe a capacidade atual relatada do volume e a capacidade livre disponível no pool ou grupo de volume associado ao volume.

. Use a caixa *Aumentar a capacidade relatada adicionando...* para adicionar capacidade à capacidade relatada disponível atualmente. Você pode alterar o valor da capacidade para exibir em mebibytes (MiB), gibibytes (GiB) ou tebibytes (TiB).
. Clique em *Increase*.


.Resultados
* System Manager aumenta a capacidade do volume com base na sua seleção.
* Selecione o menu: Home[View Operations in Progress] para visualizar o progresso da operação de aumento de capacidade que está sendo executada para o volume selecionado. Essa operação pode ser demorada e pode afetar o desempenho do sistema.


.Depois que você terminar
Após expandir a capacidade do volume, você deve aumentar manualmente o tamanho do sistema de arquivos para que corresponda. Como fazer isso depende do sistema de arquivos que você está usando. Consulte a documentação do seu sistema operacional para obter detalhes.
