---
permalink: sm-storage/overview-hosts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hosts 
summary: Você pode configurar hosts e clusters de hosts, que definem as conexões entre o array de storage e os servidores de dados. 
---
= Aprenda sobre hosts e clusters de hosts no SANtricity software
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar hosts e clusters de hosts, que definem as conexões entre o array de storage e os servidores de dados.



== O que são hosts e clusters de hosts?

Um _host_ é um servidor que envia operações de E/S para um volume em um array de storage. Um _host cluster_ é um grupo de hosts, que você pode criar para atribuir os mesmos volumes a vários hosts.

Saiba mais:

* link:host-terminology.html["Terminologia do host"]
* link:access-volumes.html["Acessar volumes"]
* link:maximum-number-of-luns.html["Número máximo de LUNs"]




== Como faço para configurar hosts e clusters de hosts?

Para definir conexões de host, você pode acessar menu:Storage[Hosts] para configurar o host manualmente. Se desejar que dois ou mais hosts compartilhem o acesso ao mesmo conjunto de volumes, você pode então definir um cluster e atribuir os volumes a esse cluster.

Saiba mais:

* link:manual-host-creation.html["Criação manual de host"]
* link:how-volumes-are-assigned-to-hosts-and-host-clusters.html["Como os volumes são atribuídos a hosts e clusters de hosts"]
* link:workflow-for-creating-hosts-and-assigning-volumes.html["Fluxograma para criação de hosts e atribuição de volumes"]
* link:create-host-manually.html["Criar host manualmente"]
* link:create-host-cluster.html["Criar cluster de hosts"]
* link:assign-volumes.html["Atribuir volumes aos hosts"]




== Informações relacionadas

Saiba mais sobre tarefas relacionadas a hosts:

* link:../sm-settings/set-automatic-load-balancing.html["Defina o balanceamento de carga automático"]
* link:../sm-settings/set-host-connectivity-reporting.html["${post_edited_translations.segment}"]
* link:../sm-settings/change-default-host-type.html["${post_edited_translations.segment}"]

