---
permalink: sm-storage/remove-member-volumes-from-a-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remove, member volume, snapshot, consistency group 
summary: Você pode remover um volume membro de um grupo de consistência de Snapshot existente. 
---
= Remover um volume membro de um grupo de consistência de Snapshot no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode remover um volume membro de um grupo de consistência de Snapshot existente.

.Sobre esta tarefa
Ao remover um volume membro de um grupo de consistência de Snapshot, System Manager exclui automaticamente os objetos de Snapshot associados a esse volume membro.

.Passos
. Selecione o menu: storage[Snapshots].
. Clique na guia *Snapshot Consistency Groups*.
. Expanda o grupo de consistência de Snapshot que deseja modificar selecionando o sinal de mais (+) ao lado dele.
. Selecione o volume do membro que você deseja remover e clique em *Remover*.
. Confirme que deseja realizar a operação e, em seguida, clique em *Remover*.


.Resultados
System Manager executa as seguintes ações:

* Exclui todas as imagens de Snapshot e volumes de Snapshot associados ao volume membro.
* Exclui o grupo de Snapshot associado ao volume membro.
* O volume de membro não é alterado ou excluído de nenhuma outra forma.

