---
permalink: sm-storage/rtv-modify-connection-settings-for-remote-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, modify, connection, settings, remote, storage 
summary: Você pode editar, adicionar ou excluir configurações de conexão para qualquer configuração de storage por meio da opção View/Edit Settings. 
---
= Modifique as configurações de conexão para storage remoto no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode editar, adicionar ou excluir configurações de conexão para qualquer configuração de storage por meio da opção View/Edit Settings.

.Sobre esta tarefa
Alterar as propriedades de conexão afetará as importações em andamento. Para evitar interrupções, faça alterações nas propriedades de conexão somente quando as importações não estiverem em execução.

.Passos
. Selecione o menu: storage [remote storage].
. Na lista, selecione o objeto de storage remoto que deseja modificar.
. Clique em *Ver/Editar Settings*.
+
A caixa de diálogo Configurações de storage remoto é exibida.

. Clique na guia *Connection Properties*.
+
São exibidas as configurações de endereço IP e porta configuradas para a importação do storage remoto.

. Execute uma das seguintes ações:
+
** *Editar* -- Clique em *Editar* ao lado do item de linha correspondente para o objeto de storage remoto. Insira o endereço IP revisado e/ou as informações de porta nos campos.
** *Adicionar* -- Clique em *Adicionar* e, em seguida, insira o novo endereço IP e as informações da porta nos campos fornecidos. Clique em *Adicionar* para confirmar e, em seguida, a nova conexão aparecerá na lista de objetos de storage remoto.
** *Excluir* -- Selecione a conexão desejada na lista e clique em *Excluir*. Confirme a operação digitando  `delete` no campo fornecido e clique em *Excluir*. A conexão é removida da lista de objetos de storage remoto.


. Clique em *Salvar*.
+
As configurações de conexão modificadas são aplicadas ao objeto de storage remoto.


