---
permalink: sm-storage/rtv-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage, terms 
summary: Saiba como os termos de armazenamento remoto se aplicam ao seu array de storage. 
---
= Aprenda sobre a terminologia de armazenamento remoto no software SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saiba como os termos de armazenamento remoto se aplicam ao seu array de storage.

[cols="25h,~"]
|===
| Termo | Descrição 


 a| 
IQN
 a| 
Identificador iSCSI Qualified Name (IQN), que é um nome exclusivo para um iniciador iSCSI ou alvo.



 a| 
LUN
 a| 
Número da unidade lógica, que é usado para identificar uma unidade lógica que pode ser apresentada a um host para acesso.



 a| 
Sistema de storage remoto
 a| 
O sistema de storage onde os dados residem inicialmente. O sistema de storage remoto pode ser um modelo E-Series ou um sistema de outro fornecedor.



 a| 
Dispositivo de storage remoto
 a| 
O dispositivo físico ou lógico onde os dados são inicialmente armazenados no sistema remoto. Em um sistema de storage E-Series, isso é chamado de "volume".



 a| 
Objeto de storage remoto
 a| 
Um objeto que contém informações que permitem ao sistema E-Series identificar e conectar-se ao sistema de storage remoto. Essas informações incluem o IQN e os endereços IP do sistema de storage remoto. O objeto de storage remoto representa a comunicação entre o sistema de storage remoto e o sistema E-Series.



 a| 
Volume de storage remoto
 a| 
Um volume padrão no sistema E-Series que permite o acesso a dados de um dispositivo de storage remoto.



 a| 
Volume
 a| 
Um contêiner no qual os dados são armazenados. É o componente lógico criado para que o host acesse os dados.

|===