---
permalink: sm-mirroring/deactivate-synchronous-mirroring.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, deactivate, synchronous, mirroring, adapter, host, bus, 
summary: 'Você pode desativar o recurso de espelhamento síncrono em um array de storage para restabelecer o uso normal da porta 4 do adaptador de barramento de host (HBA) host, que era reservada para a transmissão de dados do espelhamento.' 
---
= Desativar espelhamento síncrono no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode desativar o recurso de espelhamento síncrono em um array de storage para restabelecer o uso normal da porta 4 do adaptador de barramento de host (HBA) host, que era reservada para a transmissão de dados do espelhamento.

.Antes de começar
Você deve ter excluído todos os relacionamentos de espelhamento síncrono. Verifique se todos os pares espelhados foram excluídos do array de storage.

.Passos
. Selecione o menu: Storage [Espelhamento Síncrono].
. Selecione o menu: tarefas incomuns [Desativar].
+
O sistema exibe uma confirmação.

. Selecione *Yes* para confirmar.


.Resultados
* A porta 4 do host HBA do controlador, que era dedicada à comunicação de espelhamento síncrono, agora pode aceitar solicitações de leitura e gravação do host.
* Os volumes de capacidade reservada no array de storage são eliminados.

