---
permalink: sm-mirroring/faq-sync-mirroring.html 
sidebar: sidebar 
keywords:  
summary: Esta FAQ pode ajudar se você estiver apenas procurando uma resposta rápida para uma pergunta. 
---
= Perguntas frequentes sobre espelhamento síncrono para o SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta FAQ pode ajudar se você estiver apenas procurando uma resposta rápida para uma pergunta.



== Como o espelhamento assíncrono difere do espelhamento síncrono?

O recurso de espelhamento assíncrono difere do recurso de espelhamento síncrono de uma maneira essencial: captura o estado do volume de origem em um determinado momento e copia apenas os dados que foram alterados desde a última captura de imagem.

Com espelhamento síncrono, o estado do volume primário não é capturado em um determinado momento, mas sim reflete todas as alterações que foram feitas no volume primário para o volume secundário. O volume secundário é idêntico ao volume primário em todos os momentos porque, com esse tipo de espelhamento, cada vez que uma gravação é feita no volume primário, uma gravação é feita no volume secundário. O host não recebe uma confirmação de que a gravação foi bem-sucedida até que o volume secundário seja atualizado com sucesso com as alterações feitas no volume primário.

Com espelhamento assíncrono, o array de storage remoto não está totalmente sincronizado com o array de storage local, portanto, se o aplicativo precisar fazer a transição para o array de storage remoto devido a uma perda do array de storage local, algumas transações poderão ser perdidas.

Comparação entre recursos de espelhamento:

[cols="1a,1a"]
|===
| Espelhamento assíncrono | Espelhamento síncrono 


 a| 
*Método de replicação*



 a| 
* *Ponto no tempo*
+
O espelhamento é feito sob demanda ou automaticamente de acordo com uma programação definida pelo usuário. As programações podem ser definidas com granularidade de minutos. O tempo mínimo entre sincronizações é 10 minutos.


 a| 
* *Contínuo*
+
O espelhamento é executado automaticamente continuamente, copiando dados de cada gravação do host.





 a| 
*Capacidade reservada*



 a| 
* *Múltiplo*
+
É necessário um volume de capacidade reservada para cada par espelhado.


 a| 
* *Único*
+
É necessário um único volume de capacidade reservada para todos os volumes espelhados.





 a| 
*Comunicação*



 a| 
* *iSCSI e Fibre Channel*
+
Suporta interfaces iSCSI e Fibre Channel entre arrays de storage.


 a| 
* *Fibre Channel*
+
Suporta apenas interfaces Fibre Channel entre arrays de storage.





 a| 
*Distância*



 a| 
* *Ilimitado*
+
Suporte para distâncias praticamente ilimitadas entre o array de storage local e o array de storage remoto, sendo a distância normalmente limitada apenas pelas capacidades da rede e pela tecnologia de extensão de canal.


 a| 
* *Restrito*
+
Normalmente, deve estar a cerca de 10 km (6,2 milhas) do array de storage local para atender aos requisitos de latência e desempenho do aplicativo.



|===


== Espelhamento síncrono - Por que não vejo todos os meus volumes?

Ao selecionar um volume primário para um par espelhado, uma lista mostra todos os volumes elegíveis.

Os volumes que não são elegíveis para uso não são exibidos nessa lista. Volumes podem não ser elegíveis por qualquer um dos seguintes motivos:

* O volume é um volume não padrão, como um volume Snapshot ou um volume fino.
* O volume não está otimizado.
* O volume já está participando de uma relação de espelhamento.




== Espelhamento síncrono - Por que não vejo todos os volumes no array de storage remoto?

Ao selecionar um volume secundário no array de storage remoto, uma lista mostra todos os volumes elegíveis para esse par espelhado.

Quaisquer volumes que não são elegíveis para uso não são exibidos nessa lista. Volumes podem não ser elegíveis por qualquer um dos seguintes motivos:

* O volume é um volume não padrão, como um volume Snapshot ou um volume fino.
* O volume não está otimizado.
* O volume já está participando de uma relação de espelhamento.
* Se você estiver usando Data Assurance (DA), o volume primário e o volume secundário devem ter as mesmas configurações de DA.
+
** Se o volume principal estiver habilitado para DA, o volume secundário também deve estar habilitado para DA.
** Se o volume principal não estiver habilitado para DA, o volume secundário não deve estar habilitado para DA.






== Espelhamento síncrono - o que preciso saber antes de criar um par espelhado?

Você configura pares espelhados na interface SANtricity Unified Manager e, em seguida, gerencia os pares no SANtricity System Manager.

Antes de criar um par espelhado, siga estas orientações:

* Você precisa ter dois arrays de storage.
* Cada array de storage deve ter dois controladores.
* Cada controlador, tanto no array primário quanto no array secundário, deve ter uma porta de gerenciamento Ethernet configurada e deve estar conectado à sua rede.
* Seus arrays de storage local e remoto estão conectados por meio de uma malha Fibre Channel.
* Os arrays de storage possuem uma versão mínima de firmware de 7.84. (Cada um deles pode executar diferentes versões de sistema operacional.)
* Você deve saber a senha dos arrays de storage local e remoto.
* Você precisa ter capacidade livre suficiente no array de storage remoto para criar um volume secundário igual ou maior que o volume primário que você deseja espelhar.
* Você instalou o Web Services Proxy e Unified Manager. Os pares espelhados são configurados na interface do Unified Manager.
* Os dois arrays de storage são detectados no Unified Manager.




== Qual o impacto da prioridade de sincronização nas taxas de sincronização?

A prioridade de sincronização define quanto tempo de processamento é alocado para atividades de sincronização em relação ao desempenho do sistema.

O controlador proprietário do volume primário executa essa operação em segundo plano. Ao mesmo tempo, o controlador proprietário processa gravações de E/S locais no volume primário e gravações remotas associadas no volume secundário. Como a ressincronização desvia recursos de processamento do controlador da atividade de E/S, a ressincronização pode ter um impacto no desempenho do aplicativo host.

Tenha essas diretrizes em mente para ajudá-lo a determinar quanto tempo uma prioridade de sincronização pode levar e como as prioridades de sincronização podem afetar o desempenho do sistema.

.Sobre taxas de prioridade de sincronização
[%collapsible]
====
Estas taxas de prioridade estão disponíveis:

* Mais baixo
* Baixo
* Médio
* Alto
* Mais alto


A taxa de prioridade mais baixa oferece suporte ao desempenho do sistema, mas a ressincronização demora mais. A taxa de prioridade mais alta oferece suporte à ressincronização, mas o desempenho do sistema pode ser comprometido.

====
Essas diretrizes aproximam, de forma geral, as diferenças entre as prioridades.

[cols="35h,~"]
|===
| Taxa de prioridade para sincronização completa | Tempo decorrido em comparação com a taxa de sincronização mais alta 


 a| 
Mais baixo
 a| 
Aproximadamente oito vezes mais longo do que na taxa de prioridade mais alta.



 a| 
Baixo
 a| 
Aproximadamente seis vezes mais longo do que na taxa de prioridade mais alta.



 a| 
Médio
 a| 
Aproximadamente três vezes e meia mais longo do que na taxa de prioridade mais alta.



 a| 
Alto
 a| 
Aproximadamente duas vezes mais longo do que na taxa de prioridade mais alta.

|===
O tamanho do volume e as cargas de taxa de E/S do host afetam as comparações de tempo de sincronização.



== Por que é recomendável usar uma política de sincronização manual?

A ressincronização manual é recomendada porque permite gerenciar o processo de ressincronização de uma forma que oferece a melhor oportunidade para recuperar dados.

Se você utiliza uma política de ressincronização automática e ocorrerem problemas intermitentes de comunicação durante a ressincronização, os dados no volume secundário podem ser corrompidos temporariamente. Quando a ressincronização é concluída, os dados são corrigidos.
