---
permalink: sm-mirroring/overview-mirroring-sync.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, RVM, synchronous, mirroring, controllers, 
summary: O recurso de espelhamento síncrono fornece replicação de dados online e em tempo real entre arrays de storage a uma distância remota. 
---
= Saiba mais sobre espelhamento síncrono no software SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O recurso de espelhamento síncrono fornece replicação de dados online e em tempo real entre arrays de storage a uma distância remota.

[NOTE]
====
Este recurso não está disponível nos sistemas de storage EF600/EF600C ou EF300/EF300C.

====


== O que é espelhamento síncrono?

O espelhamento síncrono replica volumes de dados em tempo real para garantir disponibilidade contínua. Os controladores do array de storage gerenciam a operação de espelhamento, que é transparente para as máquinas host e aplicativos de software.

Esse tipo de espelhamento é ideal para continuidade dos negócios, como recuperação de desastres.

Saiba mais:

* link:how-synchronous-mirroring-works.html["Como o espelhamento síncrono funciona"]
* link:synchronous-mirroring-terminology.html["Terminologia de espelhamento síncrono"]
* link:synchronous-mirroring-status.html["Status de espelhamento síncrono"]
* link:volume-ownership-sync.html["Propriedade do volume"]
* link:role-change-of-volumes-in-a-mirrored-pair.html["Mudança de papéis entre volumes em um par espelhado"]




== Como faço para configurar espelhamento síncrono?

Você deve usar a interface do Unified Manager para realizar a configuração inicial de espelhamento entre os arrays. Uma vez configurado, você pode gerenciar os pares espelhados no System Manager.

Saiba mais:

* link:requirements-for-using-synchronous-mirroring.html["Requisitos para usar espelhamento síncrono"]
* link:workflow-for-mirroring-a-volume-synchronously.html["Fluxo de trabalho para espelhar um volume de forma síncrona"]
* link:../um-manage/create-synchronous-mirrored-pair-um.html["Criar par espelhado síncrono (no Unified Manager)"]




== Informações relacionadas

Saiba mais sobre conceitos relacionados ao espelhamento síncrono:

* link:synchronous-mirroring-what-do-i-need-to-know-before-creating-a-mirrored-pair.html["O que você precisa saber antes de criar um par espelhado"]
* link:how-does-asynchronous-mirroring-differ-from-synchronous-mirroring-async.html["Como o espelhamento assíncrono difere do espelhamento síncrono"]

