---
permalink: sm-mirroring/requirements-for-using-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, requirements, asynchronous, mirroring, 
summary: Se você planeja usar espelhamento assíncrono, tenha em mente os seguintes requisitos. 
---
= Requisitos para usar espelhamento assíncrono no software SANtricity
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você planeja usar espelhamento assíncrono, tenha em mente os seguintes requisitos.



== Unified Manager

Para habilitar e configurar o espelhamento entre dois arrays, você deve usar a interface Unified Manager. Unified Manager é instalado em um sistema host juntamente com o Web Services Proxy.

* O serviço Web Services Proxy deve estar em execução.
* Unified Manager deve estar sendo executado em seu host local por meio de uma conexão HTTPS.
* Unified Manager deve exibir certificados SSL válidos para o array de storage. Você pode aceitar um certificado autoassinado ou instalar seu próprio certificado de segurança usando Unified Manager e navegando até menu:Certificate[Certificate Management].




== Array de storage

* Você precisa ter dois arrays de storage.
* Cada array de storage deve ter dois controladores.
* Os dois arrays de storage devem ser detectados no Unified Manager.
* Cada controlador, tanto no array primário quanto no array secundário, deve ter uma porta de gerenciamento Ethernet configurada e deve estar conectado à sua rede.
* Os arrays de storage possuem uma versão mínima de firmware de 7.84. (Cada um deles pode executar diferentes versões de sistema operacional.)
* Você deve saber a senha dos arrays de storage local e remoto.
* Você precisa ter capacidade livre suficiente no array de storage remoto para criar um volume secundário igual ou maior que o volume primário que você deseja espelhar.
* Seus arrays de storage locais e remotos estão conectados por meio de uma estrutura Fibre Channel ou interface iSCSI.




== Conexões suportadas

O espelhamento assíncrono pode usar conexões FC ou iSCSI, ou ambas, para comunicação entre sistemas de storage locais e remotos. No momento da criação de um grupo de consistência de espelhamento, o administrador pode selecionar FC ou iSCSI para esse grupo se ambos estiverem conectados ao array de storage remoto. Não há failover de um tipo de canal para o outro.

O espelhamento assíncrono usa as portas de E/S do lado do host do array de storage para transmitir dados espelhados do lado primário para o lado secundário.

* *Espelhamento através de uma interface Fibre Channel (FC)*
+
Cada controlador do array de storage dedica sua porta host FC de número mais alto às operações de espelhamento.

+
Se o controlador tiver tanto portas FC básicas quanto portas FC de placa de interface de host (HIC), a porta de número mais alto estará em uma HIC. Qualquer host conectado à porta dedicada será desconectado e nenhuma solicitação de login de host será aceita. As solicitações de E/S nessa porta são aceitas somente de controladores que participam de operações de espelhamento.

+
As portas de espelhamento dedicadas devem ser conectadas a um ambiente de malha FC que suporte as interfaces de serviço de diretório e serviço de nomes. Em particular, FC-AL e ponto a ponto não são suportados como opções de conectividade entre os controladores que participam de relações de espelhamento.

* *Espelhamento através de uma interface iSCSI*
+
Ao contrário do FC, iSCSI não requer uma porta dedicada. Quando o espelhamento assíncrono é usado em ambientes iSCSI, não é necessário dedicar nenhuma das portas iSCSI front-end do array de storage para uso com espelhamento assíncrono; essas portas são compartilhadas tanto para o tráfego de espelhamento assíncrono quanto para as conexões de E/S do host para o array.

+
O controlador mantém uma lista de sistemas de armazenamento remoto com os quais o iniciador iSCSI tenta estabelecer uma sessão. A primeira porta que estabelece com sucesso uma conexão iSCSI é usada para toda a comunicação subsequente com esse array de storage. Se a comunicação falhar, uma nova sessão é tentada usando todas as portas disponíveis.

+
As portas iSCSI são configuradas no nível do array, porta por porta. A comunicação entre controladores para mensagens de configuração e transferência de dados utiliza as configurações globais, incluindo as configurações para:

+
** VLAN: os sistemas local e remoto devem ter a mesma configuração de VLAN para comunicar
** Porta de escuta iSCSI
** Quadros jumbo
** Prioridade Ethernet
+
[NOTE]
====
A comunicação entre controladores iSCSI deve usar uma porta de conexão do host e não a porta Ethernet de gerenciamento.

====


+
O espelhamento assíncrono usa as portas de E/S do host do array de storage para transmitir dados espelhados do lado primário para o lado secundário. Como o espelhamento assíncrono é destinado a redes de maior latência e menor custo, conexões iSCSI (e, portanto, baseadas em TCP/IP) são uma boa opção para ele. Quando o espelhamento assíncrono é usado em ambientes iSCSI, não é necessário dedicar nenhuma das portas iSCSI front-end do array de storage para uso com espelhamento assíncrono; essas portas são compartilhadas tanto para o tráfego de espelhamento assíncrono quanto para as conexões de E/S do host para o array.



[NOTE]
====
O E4000 não suporta espelhamento assíncrono ao usar o protocolo iSCSI.

====


== Candidatos a volume espelhado

* Nível RAID, parâmetros de armazenamento em cache e tamanho do segmento podem ser diferentes nos volumes primário e secundário de um par espelhado assíncrono.
+

NOTE: Para controladores EF600 e EF300, os volumes primário e secundário de um par espelhado assíncrono devem corresponder ao mesmo protocolo, nível de bandeja, tamanho de segmento, tipo de segurança e nível RAID. Pares espelhados assíncronos não elegíveis não aparecerão na lista de volumes disponíveis.

* O volume secundário deve ser pelo menos tão grande quanto o volume primário.
* Um volume pode participar de apenas um relacionamento de espelhamento.
* Os volumes candidatos devem compartilhar as mesmas capacidades de segurança de dados.
+
** Se o volume primário for compatível com FIPS, o volume secundário deve ser compatível com FIPS.
** Se o volume primário for compatível com FDE, o volume secundário deve ser compatível com FDE.
** Se o volume primário não estiver usando Drive Security, o volume secundário não deve estar usando Drive Security.


* Os volumes primário e secundário devem compartilhar o mesmo tipo de unidade. A combinação de unidades NVMe e SAS entre volumes primário e secundário não é suportada.
* Os volumes primário e secundário não devem ter Resource Partitioning ativado.




== Capacidade reservada

* É necessário um volume de capacidade reservada para um volume primário e para um volume secundário em um par espelhado para registrar informações de gravação para recuperação de reinicializações do controlador e outras interrupções temporárias.
* Como tanto o volume primário quanto o volume secundário em um par espelhado exigem capacidade reservada adicional, você deve garantir que haja capacidade livre disponível em ambos os storage arrays na relação de espelhamento.
* O volume de capacidade reservado deve compartilhar o mesmo tipo de unidade que seus volumes de espelhamento associados.
+
** Se o volume de capacidade reservada for criado em unidades NVMe, seus volumes espelhados também devem ser criados em unidades NVMe.
** Se o volume de capacidade reservada for criado em unidades SAS, seus volumes espelhados também deverão ser criados em unidades SAS.






== Recurso de segurança da unidade

* Se você estiver usando unidades com recursos de segurança, o volume primário e o volume secundário devem ter configurações de segurança compatíveis. Essa restrição não é aplicada; portanto, você deve verificá-la por conta própria.
* Se você estiver usando unidades com recursos de segurança, o volume primário e o volume secundário devem usar o mesmo tipo de unidade. Essa restrição não é obrigatória; portanto, você deve verificar por conta própria.
* Se você estiver usando Data Assurance (DA), o volume primário e o volume secundário devem ter as mesmas configurações de DA.

