---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, admin password 
summary: Você deve configurar o array de storage com uma senha de administrador para protegê-lo contra acesso não autorizado. 
---
= Gerenciar a proteção por senha no SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar o array de storage com senhas para protegê-lo contra acesso não autorizado.



== Definir e alterar senhas

Ao iniciar System Manager pela primeira vez, você será solicitado a definir uma senha de administrador. Qualquer usuário que possua a senha de administrador pode fazer alterações de configuração no array de storage, como adicionar, alterar ou remover objetos ou configurações. Para definir a senha de administrador durante a inicialização, consulte link:../san-getstarted/access-sam.html["Acesse o System Manager"].

Por motivos de segurança, você só pode tentar inserir uma senha cinco vezes antes que o array de storage entre em estado de "bloqueio". Nesse estado, o array de storage rejeitará as tentativas subsequentes de senha. Você deve aguardar 10 minutos para que o array de storage retorne ao estado "normal" antes de tentar inserir uma senha novamente.

Além da senha de administrador, o array de storage inclui perfis de usuário predefinidos com uma ou mais funções mapeadas a eles. Para obter mais informações, consulte link:../sm-settings/permissions-for-mapped-roles.html["Permissões para funções mapeadas"]. Os perfis de usuário e os mapeamentos não podem ser alterados. Somente as senhas podem ser modificadas. Se você deseja alterar a senha de administrador ou outras senhas de usuário, consulte link:../sm-settings/change-passwords.html["Alterar senhas"].



== Digite novamente as senhas após o término da sessão

O sistema solicita a senha apenas uma vez durante uma sessão de gerenciamento. No entanto, uma sessão expira após 30 minutos de inatividade, momento em que você deve inserir a senha novamente. Se outro usuário gerenciando o mesmo array de storage a partir de outro cliente de gerenciamento alterar a senha enquanto sua sessão estiver em andamento, você será solicitado a inserir a senha na próxima vez que tentar realizar uma operação de configuração ou de visualização.

Você pode ajustar o tempo limite da sessão ou pode desativar o tempo limite da sessão completamente. Veja link:../sm-settings/manage-session-timeouts-sam.html["Gerenciar tempos limite de sessão"].



== Remover unidades ou proteção por senha

Se você remover unidades protegidas por senha ou quiser desativar a proteção por senha, esteja ciente do seguinte:

* *Se você remover unidades com proteção por senha* -- A senha é armazenada em uma área reservada de cada unidade no array de storage. Se você remover todas as unidades de um array de storage, a senha deixará de funcionar. Para corrigir essa condição, reinstale uma das unidades originais no array de storage.
* *Se desejar remover a proteção por senha* -- Se não quiser mais que os comandos sejam protegidos por senha, digite a senha de administrador atual e deixe as caixas de texto da nova senha em branco.


[CAUTION]
====
Executar comandos de configuração em um array de storage pode causar danos graves, incluindo perda de dados. Por esse motivo, você deve sempre definir uma senha de administrador para seu array de storage. Use uma senha de administrador longa com pelo menos 15 caracteres alfanuméricos para aumentar a segurança.

====