---
permalink: sm-interface/home-page.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, home page 
summary: A página inicial fornece uma visão geral do painel de controle para o gerenciamento diário do seu array de storage. Ao fazer login no System Manager, a página inicial é a primeira tela exibida. 
---
= Saiba mais sobre a página inicial do SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A página inicial fornece uma visão geral do painel de controle para o gerenciamento diário do seu array de storage. Ao fazer login no SANtricity System Manager, a página inicial é a primeira tela exibida.

O painel de controle é composto por quatro áreas de resumo que contêm informações importantes sobre o estado e a integridade do seu array de storage. Você pode encontrar mais informações na área de resumo.

* *Notificações*
+
A área de Notificações exibe notificações de problemas que indicam o status do array de storage e seus componentes. Além disso, este portlet exibe alertas automatizados que podem ajudar você a solucionar problemas antes que eles afetem outras áreas do seu ambiente de storage.

* *Desempenho*
+
A área Desempenho permite comparar e contrastar o uso de recursos ao longo do tempo. Você pode visualizar as métricas de desempenho do array de storage para tempo de resposta (IOPS), taxas de transferência (MiB/s) e a quantidade de capacidade de processamento utilizada (CPU).

* *Capacidade*
+
A área Capacidade exibe um gráfico com a capacidade alocada, capacidade de storage livre e capacidade de storage não atribuída em seu array de storage.

* *Hierarquia de storage*
+
A área Hierarquia de Armazenamento fornece uma visão organizada dos vários componentes de hardware e objetos de storage gerenciados pelo seu array de storage. Clique na seta suspensa para executar uma determinada ação nesse componente de hardware ou objeto de storage.


