---
permalink: sm-interface/recover-from-problems-using-recovery-guru.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, Recovery Guru 
summary: O Recovery Guru é um componente do System Manager que diagnostica problemas no array de storage e recomenda procedimentos de recuperação para corrigi-los. 
---
= Recupere-se de problemas usando o SANtricity System Manager Recovery Guru
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Recovery Guru é um componente do SANtricity System Manager que diagnostica problemas no array de storage e recomenda procedimentos de recuperação para corrigi-los.

.Passos
. Selecione *Home*.
. Clique no link com a etiqueta *Recuperar de _n_ problemas* no centro-topo da janela.
+
A caixa de diálogo Recovery Guru é exibida.

. Selecione o primeiro problema exibido na lista de resumo e siga as instruções do procedimento de recuperação para corrigir o problema. Onde necessário, utilize as instruções de substituição para substituir os componentes com falha. Repita esta etapa para cada problema listado.
+
Vários problemas em um array de storage podem estar relacionados. Nesse caso, a ordem em que os problemas são corrigidos pode afetar o resultado. Selecione e corrija os problemas na ordem em que eles estão listados na lista de resumo.

+
Múltiplas falhas em um compartimento da fonte de alimentação são agrupadas e listadas como um único problema na lista de resumo. Múltiplas falhas em um compartimento do ventilador também são listadas como um único problema.

. Para garantir que o procedimento de recuperação foi bem-sucedido, clique em *Recheck*.
+
Se você selecionou um problema para um grupo de espelhamento assíncrono ou um membro de um grupo de espelhamento assíncrono, clique em *Limpar* primeiro para limpar a falha do controlador e, em seguida, clique em *Verificar novamente* para remover o evento do Recovery Guru.

+
Se todos os problemas forem corrigidos, o ícone do array de storage eventualmente mudará de "Precisa de Atenção" para "Ideal". Para alguns problemas, um ícone "Corrigindo" aparece enquanto uma operação, como reconstrução, está em andamento.

. *Opcional:* Para salvar as informações do Recovery Guru em um arquivo, clique no ícone *Save*.
+
O arquivo é salvo na pasta Downloads do seu navegador com o nome  `recovery-guru-failure-yyyy-mm-dd-hh-mm-ss-mmm.html`.

. Para imprimir as informações do Recovery Guru, clique no ícone *Print*.

