---
permalink: sm-hardware/configure-management-ports.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, management, port, 
summary: O controlador inclui uma porta Ethernet utilizada para gerenciamento do sistema. Se necessário, você pode alterar seus parâmetros de transmissão e endereços IP. 
---
= Configurar a porta de gerenciamento no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O controlador inclui uma porta Ethernet utilizada para gerenciamento do sistema. Se necessário, você pode alterar seus parâmetros de transmissão e endereços IP.

.Sobre esta tarefa
Durante este procedimento, você seleciona a porta 1 e, em seguida, determina a velocidade e o método de endereçamento da porta. A porta 1 conecta-se à rede onde o cliente pode acessar o controlador e System Manager.

[NOTE]
====
Não utilize a porta 2 em nenhum dos controladores. A porta 2 é reservada para uso do suporte técnico.

====
.Passos
. Selecione *Hardware*.
. Se a imagem mostrar as unidades, clique na guia *Controllers & Components*.
+
O gráfico muda para mostrar os controladores em vez das unidades de disco.

. Clique no controlador com a porta de gerenciamento que você deseja configurar.
+
O menu de contexto do controlador é exibido.

. Selecione *Configurar portas de gerenciamento*.
+
A caixa de diálogo Configure Management Ports é aberta.

. Certifique-se de que a porta 1 esteja visível e clique em *Next*.
. Selecione as configurações da porta de configuração e clique em *Next*.
+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Campo | Descrição 


 a| 
Velocidade e modo duplex
 a| 
Mantenha a configuração de negociação automática se desejar que o System Manager determine os parâmetros de transmissão entre o array de storage e a rede; ou, se souber a velocidade e o modo da sua rede, selecione os parâmetros na lista suspensa. Somente as combinações válidas de velocidade e modo duplex aparecem na lista.



 a| 
Habilitar IPv4 / Habilitar IPv6
 a| 
Selecione uma ou ambas as opções para ativar o suporte para redes IPv4 e IPv6.

|===
====
+
Se você selecionar *Enable IPv4*, uma caixa de diálogo será aberta para selecionar as configurações de IPv4 após você clicar em *Next*. Se você selecionar *Enable IPv6*, uma caixa de diálogo será aberta para selecionar as configurações de IPv6 após você clicar em *Next*. Se você selecionar ambas as opções, a caixa de diálogo para as configurações de IPv4 será aberta primeiro e, em seguida, após você clicar em *Next*, a caixa de diálogo para as configurações de IPv6 será aberta.

. Configurar as definições de IPv4 e/ou IPv6, seja automaticamente ou manualmente.
+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Campo | Descrição 


 a| 
Obter automaticamente a configuração do servidor DHCP
 a| 
Selecione esta opção para obter a configuração automaticamente.



 a| 
Especificar manualmente a configuração estática
 a| 
Selecione esta opção e, em seguida, insira o endereço IP do controlador. (Se desejar, você pode copiar e colar endereços nos campos.) Para IPv4, inclua a máscara de sub-rede e o gateway. Para IPv6, inclua o endereço IP roteável e o endereço IP do roteador.


NOTE: Se você alterar a configuração do endereço IP, perderá o caminho de gerenciamento para o array de storage. Se você usa SANtricity Unified Manager para gerenciar arrays globalmente em sua rede, abra a interface de usuário e acesse o menu:Manage[Discover]. Se você usa SANtricity Storage Manager, você deve remover o dispositivo da Enterprise Management Window (EMW), adicioná-lo novamente à EMW selecionando o menu:Edit[Add Storage Array] e, em seguida, inserir o novo endereço IP.

|===
====
. Clique em *Concluir*.


.Resultados
A configuração da porta de gerenciamento é exibida nas configurações do controlador, guia Portas de Gerenciamento.
