---
permalink: sm-hardware/solid-state-disks-ssds.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, solid, state, disk, SSD 
summary: 'Discos de estado sólido (SSDs) são dispositivos de storage que utilizam memória de estado sólido (flash) para armazenar dados de forma permanente. SSDs emulam discos rígidos convencionais e estão disponíveis com as mesmas interfaces que os discos rígidos utilizam.' 
---
= Saiba mais sobre Solid State Disks (SSDs) no SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Discos de estado sólido (SSDs) são dispositivos de storage que utilizam memória de estado sólido (flash) para armazenar dados de forma permanente. SSDs emulam discos rígidos convencionais e estão disponíveis com as mesmas interfaces que os discos rígidos utilizam.



== Vantagens dos SSDs

As vantagens dos SSDs em relação aos discos rígidos incluem:

* Inicialização mais rápida (sem spin up)
* Latência mais baixa
* Maior número de operações de entrada/saída por segundo (IOPS)
* Maior confiabilidade com menos peças móveis
* Menor consumo de energia
* Menos calor produzido e menos necessidade de refrigeração




== Identificando SSDs

Na página de Hardware, você pode localizar os SSDs na visualização da prateleira frontal. Procure por baias de unidade que exibem um ícone de raio, o que indica que um SSD está instalado.



== Grupos de volume

Todas as unidades em um grupo de volume devem ser do mesmo tipo de mídia (todas SSDs ou todas hard drives). Grupos de volume não podem conter uma mistura de tipos de mídia ou tipos de interface.



== Armazenamento em cache

O armazenamento em cache de gravação do controlador está sempre ativado para SSDs. O armazenamento em cache de gravação melhora o desempenho e prolonga a vida útil do SSD.

Além do cache do controlador, você pode implementar o recurso de cache SSD para melhorar o desempenho geral do sistema. No cache SSD, os dados são copiados dos volumes e armazenados em dois volumes RAID internos (um por controlador).
