---
permalink: sm-hardware/turn-on-drive-locator-light.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, turn, drive, locator, light, LEDs 
summary: Na página Hardware, você pode ativar a luz indicadora para encontrar a localização física de uma unidade no array de storage. 
---
= Ative a luz localizadora de unidade no SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Na página Hardware, você pode ativar a luz indicadora para encontrar a localização física de uma unidade no array de storage.

.Sobre esta tarefa
Você pode localizar unidades individuais ou múltiplas exibidas na página de Hardware.

.Passos
. Selecione *Hardware*.
. Para localizar uma ou mais unidades, faça um dos seguintes:
+
** *Unidade única* -- Na imagem da prateleira, encontre a unidade que deseja localizar fisicamente no array. (Se a imagem mostrar os controladores, clique na guia *Unidades*.) Clique na unidade para exibir o menu de contexto e selecione *Ligar luz indicadora*.
+
A luz indicadora da unidade acende. Quando você localizar fisicamente a unidade, retorne à caixa de diálogo e selecione *Desligar*.

** *Várias unidades* -- Nos campos de filtro, selecione um tipo de unidade física na lista suspensa à esquerda e um tipo de unidade lógica na lista suspensa à direita. O número de unidades que correspondem aos seus critérios é exibido no canto direito dos campos. Em seguida, você pode clicar em *Ligar luzes indicadoras* ou selecionar *Localizar todas as unidades filtradas* no menu de contexto. Quando você localizar fisicamente as unidades, retorne à caixa de diálogo e selecione *Desligar*.



