---
permalink: um-manage/import-alert-settings.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, import, alert, settings 
summary: Você pode importar configurações de alerta de um array de storage para outros arrays de storage. Essa operação em lote economiza tempo quando você precisa configurar vários arrays na rede. 
---
= Importar configurações de alerta no SANtricity Unified Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode importar configurações de alerta de um array de storage para outros arrays de storage. Essa operação em lote economiza tempo quando você precisa configurar vários arrays na rede.

.Antes de começar
* Os alertas são configurados no System Manager para o array de storage que você deseja usar como fonte (menu:Settings[Alerts]).
* A configuração existente para os arrays de storage de destino é salva no System Manager (menu: Configurações [Sistema > Salvar Configuração do Array de Storage]).


.Sobre esta tarefa
Você pode selecionar alertas por e-mail, SNMP ou syslog para a operação de importação. As configurações importadas incluem:

* *Alertas por e-mail* -- Um endereço de servidor de e-mail e os endereços de e-mail dos destinatários do alerta.
* *Alertas do syslog* -- Um endereço de servidor syslog e uma porta UDP.
* *Alertas SNMP* -- Um nome da comunidade e endereço IP para o servidor SNMP.


.Passos
. Na página Manage, clique em *Import Settings*.
+
O assistente de Configurações de Importação é aberto.

. Na caixa de diálogo Selecionar configurações, selecione *Alertas por e-mail*, *Alertas SNMP* ou *Alertas syslog* e clique em *Avançar*.
+
Uma caixa de diálogo é aberta para selecionar o array de storage de origem.

. Na caixa de diálogo Selecionar Origem, selecione o array com as configurações que deseja importar e clique em *Avançar*.
. Na caixa de diálogo Selecionar Destinos, selecione um ou mais arrays para receber as novas configurações.
+
[NOTE]
====
Matrizes de armazenamento com firmware inferior a 8.50 não estão disponíveis para seleção. Além disso, uma matriz não aparecerá nesta caixa de diálogo se Unified Manager não conseguir se comunicar com essa matriz (por exemplo, se estiver offline ou se apresentar problemas de certificado, senha ou rede).

====
. Clique em *Concluir*.
+
A página Operações exibe os resultados da operação de importação. Se a operação falhar, você pode clicar na linha correspondente para ver mais informações.



.Resultados
Os arrays de storage de destino agora estão configurados para enviar alertas aos administradores por e-mail, SNMP ou syslog.
