---
permalink: um-manage/import-directory-services-settings.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, import, directory, services, settings 
summary: Você pode importar uma configuração de serviços de diretório de um array de storage para outros arrays de storage. Essa operação em lote economiza tempo quando você precisa configurar vários arrays na rede. 
---
= Importar configurações de serviços de diretório no SANtricity Unified Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode importar uma configuração de serviços de diretório de um array de storage para outros arrays de storage. Essa operação em lote economiza tempo quando você precisa configurar vários arrays na rede.

.Antes de começar
* Os serviços de diretório são configurados no System Manager para o array de storage que você deseja usar como fonte (menu:Settings[Gerenciamento de Acesso]).
* A configuração existente para os arrays de storage de destino é salva no System Manager (menu: Configurações [Sistema > Salvar Configuração do Array de Storage]).


.Sobre esta tarefa
As configurações importadas incluem o nome de domínio e o URL de um servidor LDAP (Lightweight Directory Access Protocol), juntamente com os mapeamentos dos grupos de usuários do servidor LDAP para as funções predefinidas do array de storage.

.Passos
. Na página Manage, clique em *Import Settings*.
+
O assistente de Configurações de Importação é aberto.

. Na caixa de diálogo Selecionar configurações, selecione *Directory services* e clique em *Next*.
+
Uma caixa de diálogo é aberta para selecionar o array de storage de origem.

. Na caixa de diálogo Selecionar Origem, selecione o array com as configurações que deseja importar e clique em *Avançar*.
. Na caixa de diálogo Selecionar Destinos, selecione um ou mais arrays para receber as novas configurações.
+
[NOTE]
====
Matrizes de armazenamento com firmware inferior a 8.50 não estão disponíveis para seleção. Além disso, uma matriz não aparecerá nesta caixa de diálogo se Unified Manager não conseguir se comunicar com essa matriz (por exemplo, se estiver offline ou se apresentar problemas de certificado, senha ou rede).

====
. Clique em *Concluir*.
+
A página Operações exibe os resultados da operação de importação. Se a operação falhar, você pode clicar na linha correspondente para ver mais informações.





== Resultados

Os arrays de storage de destino agora estão configurados com os mesmos serviços de diretório que o array de origem.
