---
permalink: um-manage/mirroring-configuration-workflow.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring, configuration, workflow 
summary: Você configura espelhamento assíncrono ou síncrono no Unified Manager e, em seguida, usa System Manager para gerenciar as sincronizações. 
---
= Fluxos de trabalho de configuração do espelhamento SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você configura espelhamento assíncrono ou síncrono no SANtricity Unified Manager e, em seguida, usa SANtricity System Manager para gerenciar as sincronizações.



== Fluxo de trabalho de espelhamento assíncrono

O espelhamento assíncrono envolve o seguinte fluxo de trabalho:

. Realize a configuração inicial no Unified Manager:
+
.. Selecione o array de storage local como a origem para a transferência de dados.
.. Crie ou selecione um grupo de consistência de espelhamento existente, que é um contêiner para o volume primário no array de storage local e o volume secundário no array de storage remoto. Os volumes primário e secundário são chamados de "par espelhado". Se você estiver criando o grupo de consistência de espelhamento pela primeira vez, especifique se deseja realizar sincronizações manuais ou agendadas.
.. Selecione um volume primário do array de storage local e, em seguida, determine sua capacidade reservada. A capacidade reservada é a capacidade física alocada para ser usada na operação de cópia.
.. Selecione um array de storage remoto como destino da transferência, um volume secundário e, em seguida, determine sua capacidade reservada.
.. Inicie a transferência inicial de dados do volume primário para o volume secundário. Dependendo do tamanho do volume, essa transferência inicial pode levar várias horas.


. Verifique o progresso da sincronização inicial:
+
.. No Unified Manager, inicie o System Manager para o array local.
.. No System Manager, visualize o status da operação de espelhamento. Quando o espelhamento estiver concluído, o status do par espelhado será "Ótimo".


. Opcionalmente, você pode reagendar ou executar manualmente as transferências de dados subsequentes no System Manager. Somente blocos novos e alterados são transferidos do volume primário para o volume secundário.
+
[NOTE]
====
Como a replicação assíncrona é periódica, o sistema pode consolidar os blocos alterados e conservar a largura de banda. Há impacto mínimo na taxa de transferência de escrita e na latência.

====




== Fluxo de trabalho de espelhamento síncrono

Espelhamento síncrono envolve o seguinte fluxo de trabalho:

. Realize a configuração inicial no Unified Manager:
+
.. Selecione um array de storage local como origem para a transferência de dados.
.. Selecione um volume primário do array de storage local.
.. Selecione um array de storage remoto como destino para a transferência de dados e, em seguida, selecione um volume secundário.
.. Selecione as prioridades de sincronização e ressincronização.
.. Inicie a transferência inicial de dados do volume primário para o volume secundário. Dependendo do tamanho do volume, essa transferência inicial pode levar várias horas.


. Verifique o progresso da sincronização inicial:
+
.. No Unified Manager, inicie o System Manager para o array local.
.. No System Manager, visualize o status da operação de espelhamento. Quando o espelhamento estiver concluído, o status do par espelhado será "Ótimo". Os dois arrays tentam permanecer sincronizados por meio de operações normais. Somente blocos novos e alterados são transferidos do volume primário para o volume secundário.


. Opcionalmente, você pode alterar as configurações de sincronização no System Manager.
+
[NOTE]
====
Como a replicação síncrona é contínua, o link de replicação entre os dois sites deve fornecer largura de banda suficiente.

====

