---
permalink: um-manage/overview-manage-groups.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, manage, groups 
summary: Na página Gerenciar Grupos, você pode criar um conjunto de grupos de array de storage para facilitar o gerenciamento. 
---
= Saiba mais sobre a visão geral de grupos no SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Na página Gerenciar Grupos, você pode criar um conjunto de grupos de array de storage para facilitar o gerenciamento.



== O que são grupos de array?

Você pode gerenciar sua infraestrutura física e virtualizada agrupando um conjunto de arrays de storage. Você pode querer agrupar arrays de storage para facilitar a execução de tarefas de monitoramento ou geração de relatórios.

Existem dois tipos de grupos:

* *Grupo Todos* -- O grupo Todos é o grupo padrão e inclui todos os arrays de storage descobertos em sua organização. O grupo Todos pode ser acessado na visualização principal.
* *Grupo criado pelo usuário* -- Um grupo criado pelo usuário inclui os arrays de storage que você seleciona manualmente para adicionar a esse grupo. Os grupos criados pelo usuário podem ser acessados na visualização principal.




== Como faço para configurar grupos?

Na página Manage Groups, você pode criar um grupo e, em seguida, adicionar arrays a esse grupo.

Saiba mais:

* link:create-storage-array-group.html["Configurar grupo de array de storage"]

