---
permalink: um-manage/overview-mirroring-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring 
summary: Utilize os recursos de espelhamento para replicar dados entre um array de storage local e um array de storage remoto, de forma assíncrona ou síncrona. 
---
= Saiba mais sobre espelhamento no SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilize os recursos de espelhamento para replicar dados entre um array de storage local e um array de storage remoto, de forma assíncrona ou síncrona.

[NOTE]
====
O espelhamento síncrono não está disponível no sistema de storage EF600/EF600C ou EF300/EF300C.

====


== O que é espelhamento?

Os aplicativos SANtricity incluem dois tipos de espelhamento -- assíncrono e síncrono. O espelhamento assíncrono copia volumes de dados sob demanda ou de acordo com um cronograma, o que minimiza ou evita o tempo de inatividade que pode resultar de corrupção de dados ou perda. O espelhamento síncrono replica volumes de dados em tempo real para garantir disponibilidade contínua.

Saiba mais:

* link:mirroring-overview.html["Como o espelhamento funciona"]
* link:mirroring-terminology.html["Terminologia de espelhamento"]




== Como configuro o espelhamento?

Você configura espelhamento assíncrono ou síncrono no Unified Manager e, em seguida, usa System Manager para gerenciar as sincronizações.

Saiba mais:

* link:mirroring-configuration-workflow.html["Fluxo de trabalho de configuração de espelhamento"]
* link:requirements-for-using-mirroring.html["Requisitos para usar espelhamento"]
* link:create-asynchronous-mirrored-pair-um.html["Criar par espelhado assíncrono"]
* link:create-synchronous-mirrored-pair-um.html["Criar par espelhado síncrono"]

