---
permalink: um-manage/perform-pre-upgrade-health-check.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, perform, pre-upgrade, health, check 
summary: Uma verificação de integridade é executada como parte do processo de atualização, mas você também pode executar uma verificação de integridade separadamente antes de começar. A verificação de integridade avalia os componentes do array de storage para garantir que a atualização possa prosseguir. 
---
= Execute uma verificação de integridade pré-atualização no SANtricity Unified Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma verificação de integridade é executada como parte do processo de atualização, mas você também pode executar uma verificação de integridade separadamente antes de começar. A verificação de integridade avalia os componentes do array de storage para garantir que a atualização possa prosseguir.

.Passos
. Na tela principal, selecione *Gerenciar* e, em seguida, selecione menu:Upgrade Center[Verificação de integridade pré-atualização].
+
A caixa de diálogo Verificação de integridade pré-atualização é aberta e lista todos os sistemas de storage detectados.

. Se necessário, filtre ou classifique os sistemas de storage na lista, para que você possa visualizar todos os sistemas que não estão atualmente no estado Ótimo.
. Selecione as caixas de seleção dos sistemas de storage que você deseja executar na verificação de integridade.
. Clique em *Start*.
+
O progresso é exibido na caixa de diálogo enquanto a verificação de integridade é realizada.

. Quando a verificação de integridade for concluída, você pode clicar nas reticências (...) à direita de cada linha para visualizar mais informações e executar outras tarefas.
+
[NOTE]
====
Se algum dos arrays falhar na verificação de integridade, você pode ignorar esse array específico e continuar a atualização para os outros, ou pode interromper todo o processo e solucionar os problemas nos arrays que não foram aprovados.

====

