---
permalink: sm-settings/access-management-with-directory-services.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access management, directory services, 
summary: 'Para o gerenciamento de acesso, os administradores podem usar um servidor LDAP (Lightweight Directory Access Protocol) e um serviço de diretório, como o Microsoft Active Directory.' 
---
= Configurar o controle de acesso com serviços de diretório no SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para o gerenciamento de acesso, os administradores podem usar um servidor LDAP (Lightweight Directory Access Protocol) e um serviço de diretório, como o Active Directory da Microsoft.



== Fluxo de trabalho de configuração

Se um servidor LDAP e um serviço de diretório forem usados na rede, a configuração funciona da seguinte forma:

. Um administrador faz login no System Manager com um perfil de usuário que inclui permissões de Security Admin.
+
[NOTE]
====
O `admin` usuário tem acesso total a todas as funções do sistema.

====
. O administrador insere as configurações do servidor LDAP. As configurações incluem o nome de domínio, a URL e as informações da conta Bind.
. Se o servidor LDAP usar um protocolo seguro (LDAPS), o administrador carrega uma cadeia de certificados da Autoridade Certificadora (CA) para autenticação entre o servidor LDAP e o array de storage.
. Após a conexão com o servidor ser estabelecida, o administrador mapeia os grupos de usuários para as funções do array de storage. Essas funções são predefinidas e não podem ser modificadas.
. O administrador testa a conexão entre o servidor LDAP e o array de storage.
. Os usuários acessam o sistema com suas credenciais LDAP/Directory Services atribuídas.




== Gerenciamento

Ao usar serviços de diretório para autenticação, os administradores podem executar as seguintes tarefas de gerenciamento:

* Adicionar um servidor de diretório.
* Editar configurações do servidor de diretório.
* Mapear usuários LDAP para funções de usuário locais.
* Remova um servidor de diretório.

