---
permalink: sm-settings/access-management-tokens-create.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access management, create tokens 
summary: Você pode criar tokens de acesso, que são usados para autenticar com a API REST ou a interface de linha de comando em vez de um nome de usuário e senha. 
---
= Criar tokens de acesso no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar um token de acesso para autenticar-se com a API REST ou interface de linha de comando (CLI) em vez de um nome de usuário e senha.


NOTE: Tokens não possuem senhas, portanto, você deve gerenciá-los com cuidado.

.Passos
. Selecione o menu: Configurações [Access Management].
. Selecione a guia *Access Tokens*.
. Selecione *Exibir/Editar configurações de token de acesso*. Na caixa de diálogo, certifique-se de que a caixa de seleção *Habilitar tokens de acesso* esteja marcada. Clique em *Salvar* para fechar a caixa de diálogo.
. Selecione *Create Access Token*.
. Na caixa de diálogo, selecione a duração para a qual o token será válido.
+

NOTE: Após o token expirar, as tentativas de autenticação do usuário falharão.

. Clique em *Criar*.
. Na caixa de diálogo, selecione uma das seguintes:
+
** *Copiar* para salvar o texto do token na área de transferência.
** *Download* para salvar o texto do token em um arquivo.
+

NOTE: Não se esqueça de salvar o texto do token. Esta é a sua única oportunidade de visualizar o texto antes de fechar a caixa de diálogo.



. Clique em *Close*.
. Use o token da seguinte forma:
+
** *API REST*: Para usar um token em uma solicitação de API REST, adicione um cabeçalho HTTP às suas solicitações. Por exemplo:
`Authorization: Bearer _<access-token-value>_`
** *Secure CLI*: Para usar um token na CLI, adicione o valor do token na linha de comando ou use o caminho para um arquivo que contenha o valor do token. Por exemplo:
+
*** Valor do token na linha de comando: `-t _access-token-value_`
*** Caminho para um arquivo que contém o valor do token: `-T _access-token-file_`
+

NOTE: A CLI solicita ao usuário um valor de token de acesso na linha de comando se nenhum nome de usuário, senha ou token for especificado.






