---
permalink: sm-settings/add-syslog-servers-for-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, syslog, servers, alerts, 
summary: Você pode adicionar no máximo cinco servidores para alertas do syslog. 
---
= Adicione servidores syslog para alertas no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar no máximo cinco servidores para alertas do syslog.

.Antes de começar
* O endereço do servidor syslog deve estar disponível. Esse endereço pode ser um domínio totalmente qualificado, um endereço IPv4 ou um endereço IPv6.
* O número da porta UDP do servidor syslog deve estar disponível. Essa porta normalmente é 514.


.Passos
. Selecione o menu: configurações [Alertas].
. Selecione a guia *Syslog*.
. Selecione *Add Syslog Servers*.
+
A caixa de diálogo Adicionar Servidor syslog é aberta.

. Selecione *Adicionar outro servidor syslog*.
. Insira as informações para o servidor syslog e clique em *Adicionar*.
+
** *Endereço do servidor Syslog* -- Insira um domínio totalmente qualificado, um endereço IPv4 ou um endereço IPv6.
** *Porta UDP* -- Normalmente, a porta UDP para syslog é 514.


+

NOTE: Você pode configurar até cinco servidores syslog.



.Resultados
Os endereços do servidor syslog aparecem na tabela.
