---
permalink: sm-settings/change-passwords.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, passwords, user, passwords, 
summary: Você pode alterar as senhas de usuário para cada perfil de usuário no Access Management. 
---
= Alterar senhas no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar as senhas de usuário para cada perfil de usuário no Access Management.

.Antes de começar
* Você deve estar conectado como administrador local, o que inclui permissões de Root admin.
* Você deve saber a senha do administrador local.


.Sobre esta tarefa
Mantenha estas diretrizes em mente ao escolher uma senha:

* Quaisquer novas senhas de usuários locais devem atender ou exceder a configuração atual para senha mínima (em Exibir/Editar Configurações).
* As senhas diferenciam maiúsculas de minúsculas.
* Os espaços em branco no final das senhas não são removidos durante a sua criação. Tenha cuidado para incluir os espaços caso eles estejam presentes na senha.
* Para maior segurança, use pelo menos 15 caracteres alfanuméricos e altere a senha com frequência.


[NOTE]
====
Alterar a senha no System Manager também a altera na interface de linha de comando (CLI). Além disso, alterações de senha causam o encerramento da sessão ativa do usuário.

====
.Passos
. Selecione o menu: Configurações [Access Management].
. Selecione a guia *Funções de usuário local*.
. Selecione um usuário da tabela.
+
O botão Alterar Senha se torna disponível.

. Selecione *Change Password*.
+
A caixa de diálogo Alterar Senha é aberta.

. Se não houver um comprimento mínimo de senha definido para senhas de usuários locais, você pode marcar a caixa para exigir que o usuário selecionado insira uma senha para acessar o array de storage e, em seguida, você pode digitar a nova senha para o usuário selecionado.
. Digite a senha do administrador local e, em seguida, clique em *Alterar*.


.Resultados
Se o usuário estiver conectado no momento, a alteração da senha faz com que a sessão ativa do usuário seja encerrada.
