---
permalink: sm-settings/change-local-user-passwords-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, local, user, password, settings, 
summary: Você pode definir o comprimento mínimo exigido para todas as senhas de usuários locais novas ou atualizadas no array de storage. Você também pode permitir que usuários locais acessem o array de storage sem inserir uma senha. 
---
= Alterar as configurações de senha do usuário local em SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode definir o comprimento mínimo exigido para todas as senhas de usuários locais novas ou atualizadas no array de storage. Você também pode permitir que usuários locais acessem o array de storage sem inserir uma senha.

.Antes de começar
Você deve estar conectado como administrador local, o que inclui permissões de Root admin.

.Sobre esta tarefa
Mantenha estas diretrizes em mente ao definir o comprimento mínimo para senhas de usuários locais:

* As alterações de configuração não afetarão as senhas de usuários locais existentes.
* A configuração de comprimento mínimo exigido para senhas de usuários locais deve estar entre 0 e 30 caracteres.
* Quaisquer novas senhas de usuários locais devem atender ou exceder a configuração atual de comprimento mínimo.
* Não defina um comprimento mínimo para a senha se desejar que os usuários locais acessem o array de storage sem digitar uma senha.


.Passos
. Selecione o menu: Configurações [Access Management].
. Selecione a guia *Funções de usuário local*.
. Selecione o botão *View/Edit Settings*.
+
A caixa de diálogo Configurações de senha do usuário local é aberta.

. Faça uma das seguintes ações:
+
** Para permitir que os usuários locais acessem o array de storage _sem_ inserir uma senha, desmarque a caixa de seleção "Exigir que todas as senhas de usuários locais tenham pelo menos".
** Para definir um comprimento mínimo de senha para todas as senhas de usuários locais, marque a caixa de seleção "Exigir que todas as senhas de usuários locais tenham pelo menos" e então use o seletor para definir o comprimento mínimo exigido para todas as senhas de usuários locais.
+
Quaisquer novas senhas de usuários locais devem atender ou exceder a configuração atual.



. Clique em *Salvar*.

