---
permalink: sm-settings/configure-nvme-over-infiniband-ports-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, nvme, over, InfiniBand, ports, 
summary: Se o seu controlador incluir uma conexão NVMe over InfiniBand, você pode configurar as configurações da porta NVMe na página System. 
---
= Configurar NVMe sobre InfiniBand portas no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se o seu controlador incluir uma conexão NVMe over InfiniBand, você pode configurar as configurações da porta NVMe na página System.

.Antes de começar
* Seu controlador deve incluir uma porta de host NVMe sobre InfiniBand; caso contrário, as configurações de NVMe sobre InfiniBand não estarão disponíveis no System Manager.
* Você deve saber o endereço IP da conexão do host.


[NOTE]
====
As configurações e funções do NVMe over InfiniBand aparecem somente se o controlador do seu array de storage incluir uma porta NVMe over InfiniBand.

====
.Passos
. Selecione o menu: configurações [Sistema].
. Em *Configurações NVMe over InfiniBand*, selecione *Configurar portas NVMe over InfiniBand*.
. Selecione o controlador com a porta NVMe over InfiniBand que você deseja configurar. Clique em *Avançar*.
. Selecione a porta HIC que deseja configurar na lista suspensa e, em seguida, insira o endereço IP.
+
Se você estiver configurando um array de storage EF600 com um HIC compatível com 200Gb, esta caixa de diálogo exibirá dois campos de endereço IP, um para uma porta física (externa) e outro para uma porta virtual (interna). Você deve atribuir um endereço IP exclusivo para ambas as portas. Essas configurações permitem que o host estabeleça um caminho entre cada porta e que o HIC atinja o desempenho máximo. Se você não atribuir um endereço IP à porta virtual, o HIC funcionará com aproximadamente metade de sua velocidade possível.

. Clique em *Concluir*.
. Redefina a porta NVMe over InfiniBand clicando em *Sim*.

