---
permalink: sm-settings/drive-security-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, drive, security, terms, 
summary: Saiba como os termos de segurança da unidade se aplicam ao seu array de storage. 
---
= Aprenda sobre a terminologia de segurança de unidades no software SANtricity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saiba como os termos de segurança da unidade se aplicam ao seu array de storage.

[cols="25h,~"]
|===
| Termo | Descrição 


 a| 
Recurso de segurança da unidade
 a| 
Drive Security é um recurso do array de storage que fornece uma camada extra de segurança com unidades Full Disk Encryption (FDE) ou unidades Federal Information Processing Standard (FIPS). Quando essas unidades são usadas com o recurso Drive Security, elas exigem uma chave de segurança para acesso aos seus dados. Quando as unidades são fisicamente removidas do array, elas não podem operar até serem instaladas em outro array; nesse momento, elas estarão em um estado Security Locked até que a chave de segurança correta seja fornecida.



 a| 
Unidades FDE
 a| 
Unidades com criptografia de disco completa (FDE) realizam criptografia na unidade de disco no nível do hardware. O disco rígido contém um chip ASIC que criptografa os dados durante as gravações e os descriptografa durante as leituras.



 a| 
Unidades FIPS
 a| 
Unidades FIPS utilizam o Federal Information Processing Standards (FIPS) 140-2 nível 2. Essencialmente, são unidades FDE que seguem os padrões do governo dos Estados Unidos para garantir algoritmos e métodos de criptografia robustos. Unidades FIPS possuem padrões de segurança mais elevados do que unidades FDE.



 a| 
Cliente de gerenciamento
 a| 
Um sistema local (computador, tablet, etc.) que inclui um navegador para acessar System Manager.



 a| 
Frase secreta
 a| 
A frase secreta é usada para criptografar a chave de segurança para fins de backup. A mesma frase secreta usada para criptografar a chave de segurança deve ser fornecida quando a chave de segurança de backup for importada como resultado de uma migração de unidade ou troca de cabeçote. Uma frase secreta pode ter entre 8 e 32 caracteres.

[NOTE]
====
A senha para Segurança da Unidade é independente da senha de Administrador do array de storage.

====


 a| 
Unidades com capacidade de segurança
 a| 
Unidades com capacidade de segurança podem ser unidades Full Disk Encryption (FDE) ou unidades Federal Information Processing Standard (FIPS), que criptografam os dados durante as gravações e descriptografam os dados durante as leituras. Essas unidades são consideradas secure-_capable_ porque podem ser usadas para segurança adicional usando o recurso Drive Security. Se o recurso Drive Security estiver habilitado para grupos de volume e pools usados com essas unidades, as unidades se tornam secure-_enabled_.



 a| 
Unidades com segurança ativada
 a| 
Unidades com segurança habilitada são usadas com o recurso Drive Security. Quando você habilita o recurso Drive Security e, em seguida, aplica Drive Security a um pool ou grupo de volume em unidades secure-capable, as unidades passam a ser secure-enabled. O acesso de leitura e gravação está disponível somente por meio de um controlador configurado com a chave de segurança correta. Essa segurança adicional impede o acesso não autorizado aos dados em uma unidade que foi fisicamente removida do array de storage.



 a| 
Chave de segurança
 a| 
Uma chave de segurança é uma sequência de caracteres compartilhada entre as unidades e controladores com segurança habilitada em um array de storage. Sempre que a energia das unidades é desligada e ligada, as unidades com segurança habilitada entram no estado Security Locked até que o controlador aplique a chave de segurança. Se uma unidade com segurança habilitada for removida do array de storage, os dados da unidade serão bloqueados. Quando a unidade for reinstalada em um array de storage diferente, ela buscará a chave de segurança antes de tornar os dados acessíveis novamente. Para desbloquear os dados, você deve aplicar a chave de segurança original. Você pode criar e gerenciar chaves de segurança usando um dos seguintes métodos:

* Gerenciamento de chaves internas -- criar e manter chaves de segurança na memória persistente do controlador.
* Gerenciamento de chaves externas -- criar e manter chaves de segurança em um servidor de gerenciamento de chaves externo.




 a| 
Identificador da chave de segurança
 a| 
O identificador da chave de segurança é uma sequência de caracteres associada à chave de segurança durante a criação da chave. O identificador é armazenado no controlador e em todas as unidades associadas à chave de segurança.

|===