---
permalink: sm-settings/edit-syslog-server-settings-for-audit-log-records.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, edit, syslog, server, settings, audit, log, records, 
summary: 'Você pode alterar as configurações do servidor syslog usado para arquivamento de logs de auditoria e também carregar um novo certificado de Autoridade Certificadora (CA) para o servidor.' 
---
= Edite as configurações do servidor syslog para registros de log de auditoria no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar as configurações do servidor syslog usado para arquivamento de logs de auditoria e também carregar um novo certificado de Autoridade Certificadora (CA) para o servidor.

.Antes de começar
* Você precisa estar conectado com um perfil de usuário que inclua permissões de Security admin. Caso contrário, as funções de Access Management não serão exibidas.
* O endereço do servidor syslog, o protocolo e o número da porta devem estar disponíveis. O endereço do servidor pode ser um domínio totalmente qualificado, um endereço IPv4 ou um endereço IPv6.
* Se você estiver carregando um novo certificado de CA, o certificado deve estar disponível no seu sistema local.


.Passos
. Selecione o menu: Configurações [Access Management].
. Na guia log de auditoria, selecione *Configurar servidores syslog*.
+
Os servidores syslog configurados são exibidos na página.

. Para editar as informações do servidor, selecione o ícone *Editar* (lápis) à direita do nome do servidor e, em seguida, faça as alterações desejadas nos seguintes campos:
+
** *Endereço do servidor* -- Insira um domínio totalmente qualificado, um endereço IPv4 ou um endereço IPv6.
** *Protocolo* -- selecione um protocolo na lista suspensa (por exemplo, TLS, UDP ou TCP).
** *Porta* -- Insira o número da porta para o receptor syslog.


. Se você alterou o protocolo para o protocolo seguro TLS (de UDP ou TCP), clique em *Import Trusted Certificate* para carregar um certificado de CA.
. Para testar a nova conexão com o array de storage, selecione *Test All*.


.Resultados
Após a configuração, todos os novos logs de auditoria são enviados para o servidor syslog. Os logs anteriores não são transferidos.
