---
permalink: sm-settings/edit-mail-server-for-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, edit, mail, server, alerts, 
summary: Você pode alterar o endereço do servidor de e-mail e o endereço do remetente de e-mail usados para alertas por e-mail. 
---
= Editar servidor de e-mail para alertas no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar o endereço do servidor de e-mail e o endereço do remetente de e-mail usados para alertas por e-mail.

.Antes de começar
O endereço do servidor de e-mail que você está alterando precisa estar disponível. O endereço pode ser um endereço IPv4 ou IPv6, ou um nome de domínio totalmente qualificado.

[NOTE]
====
Para usar um nome de domínio totalmente qualificado, você precisa configurar um servidor DNS em ambos os controladores. Você pode configurar um servidor DNS na página Hardware.

====
.Passos
. Selecione o menu: configurações [Alertas].
. Selecione a guia *Email*.
. Selecione *Configurar Mail Server*.
+
A caixa de diálogo Configurar Servidor de Correio é aberta.

. Edite o endereço do servidor de e-mail, as informações do remetente e as informações de contato.
+
** *Endereço do servidor de e-mail* -- Edite o domínio totalmente qualificado, o endereço IPv4 ou o endereço IPv6 do servidor de e-mail.
+
[NOTE]
====
Para usar um nome de domínio totalmente qualificado, você precisa configurar um servidor DNS em ambos os controladores. Você pode configurar um servidor DNS na página Hardware.

====
** *Endereço do remetente do e-mail* -- Edite o endereço de e-mail que será usado como remetente do e-mail. Este endereço aparece no campo "De" da mensagem de e-mail.
** *Incluir informações de contato no email* -- Para editar as informações de contato do remetente, selecione esta opção e, em seguida, edite o nome e o número de telefone.


. Clique em *Salvar*.

