---
permalink: sm-settings/enable-or-disable-legacy-management-interface.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, disable, legacy, management, interface, 
summary: ${post_edited_translations.segment} 
---
= ${post_edited_translations.segment}
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
${post_edited_translations.segment}

.Sobre esta tarefa
Por padrão, a interface de gerenciamento legada está ativada. Se você desabilitá-la, o array de storage e o cliente de gerenciamento usarão um método de comunicação mais seguro (API REST sobre https); no entanto, certas ferramentas e tarefas podem ser afetadas se ela for desabilitada.

[NOTE]
====
${post_edited_translations.segment}

====
${post_edited_translations.segment}

* ${post_edited_translations.segment}
* *Desativado* -- Configuração necessária para impor a confidencialidade nas comunicações entre o array de storage e o cliente de gerenciamento, e para acessar ferramentas externas. Configuração recomendada ao configurar um Directory Server (LDAP).


.Passos
. Selecione o menu: configurações [Sistema].
. Desça até *Configurações adicionais* e clique em *Alterar interface de gerenciamento*.
. Na caixa de diálogo, clique em *Yes* para continuar.

