---
permalink: sm-settings/overview-drive-security.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, system, security, key, management, 
summary: O gerenciamento de chaves de segurança está disponível na página System. 
---
= Saiba mais sobre segurança de unidades em SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar Drive Security e o gerenciamento de chaves na página Security Key Management.



== O que é Drive Security?

_Drive Security_ é um recurso que impede o acesso não autorizado a dados em drives com segurança habilitada quando removidos do array de storage. Esses drives podem ser Full Disk Encryption (FDE) drives ou Federal Information Processing Standard (FIPS) drives. Quando drives FDE ou FIPS são fisicamente removidos do array, eles não podem operar até serem instalados em outro array, momento em que os drives ficarão em um estado de Security Locked até que a security key correta seja fornecida. Uma _security key_ é uma sequência de caracteres compartilhada entre esses tipos de drives e os controladores em um array de storage.

Saiba mais:

* link:how-the-drive-security-feature-works.html["Como funciona o recurso Drive Security"]
* link:how-security-key-management-works.html["Como funciona o gerenciamento de chaves de segurança"]
* link:drive-security-terminology.html["Terminologia de segurança de drive"]




== Como faço para configurar o gerenciamento de chaves?

Para implementar Drive Security, você deve ter unidades FDE ou FIPS instaladas no array. Para configurar o gerenciamento de chaves para essas unidades, acesse menu:Settings[Sistema > Security key management], onde você pode criar uma chave interna a partir da memória persistente do controlador ou uma chave externa a partir de um servidor de gerenciamento de chaves. Por fim, habilite Drive Security para pools e grupos de volumes selecionando "secure-capable" nas configurações do volume.

Saiba mais:

* link:create-internal-security-key.html["Criar chave de segurança interna"]
* link:create-external-security-key.html["Criar chave de segurança externa"]
* link:../sm-storage/create-pool-manually.html["Criar pool manualmente"]
* link:../sm-storage/create-volume-group.html["Criar grupos de volumes"]




== Como faço para desbloquear unidades?

Se você configurou o gerenciamento de chaves e, posteriormente, move unidades com segurança habilitada de um array de storage para outro, você deve reatribuir a chave de segurança ao novo array de storage para obter acesso aos dados criptografados nas unidades.

Saiba mais:

* link:unlock-drives-using-an-internal-security-key.html["Desbloqueie unidades ao usar o gerenciamento interno de chaves"]
* link:unlock-drives-using-an-external-security-key.html["Desbloqueie unidades ao usar o gerenciamento de chaves externas"]




== Informações relacionadas

Saiba mais sobre tarefas relacionadas à gestão de chaves:

* link:use-ca-signed-certificates-for-authentication-with-a-key-management-server.html["Use certificados assinados por CA para autenticação com um servidor de gerenciamento de chaves"]
* link:back-up-security-key.html["Fazer backup da chave de segurança"]

