---
permalink: sm-settings/overview-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, Alerts, 
summary: Você pode configurar System Manager para enviar alertas do array de storage por e-mail, traps SNMP e mensagens syslog. 
---
= Saiba mais sobre alertas no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar SANtricity System Manager para enviar alertas do array de storage por e-mail, traps SNMP e mensagens syslog.



== O que são alertas?

_Alerts_ notificam os administradores sobre eventos importantes que ocorrem no array de storage. Os eventos podem incluir problemas como falha de bateria, um componente passando de Optimal para Offline ou erros de redundância no controlador. Todos os eventos Critical são considerados "alertáveis", juntamente com alguns eventos Warning e Informational.

Saiba mais:

* link:how-alerts-work.html["Como funcionam os alertas"]
* link:alerts-terminology.html["Terminologia de alertas"]




== Como faço para configurar alertas?

Você pode configurar alertas para serem enviados como uma mensagem para um ou mais endereços de e-mail, como um trap SNMP para um servidor SNMP ou como uma mensagem para um servidor syslog. A configuração de alertas está disponível em menu:Configurações[Alertas].

Saiba mais:

* link:configure-mail-server-and-recipients-for-alerts.html["Configurar o servidor de e-mail e os destinatários para alertas"]
* link:configure-syslog-server-for-alerts.html["Configurar servidor syslog para alertas"]
* link:configure-snmp-alerts.html["Configurar alertas SNMP"]




== Informações relacionadas

Saiba mais sobre conceitos relacionados a alertas:

* link:../sm-support/overview-event-log.html["Visão geral do log de eventos"]
* link:why-are-timestamps-inconsistent-between-the-array-and-alerts.html["Registros de data e hora inconsistentes"]

