---
permalink: sm-settings/switch-from-external-to-internal-key-management.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, switch, external, internal, key, management, 
summary: Você pode alterar o método de gerenciamento da Segurança da Unidade de um servidor de chaves externo para o método interno usado pelo array de storage. A chave de segurança previamente definida para o gerenciamento de chaves externas passa a ser usada para o gerenciamento de chaves internas. 
---
= Altere do gerenciamento de chaves externas para internas no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar o método de gerenciamento da Segurança da Unidade de um servidor de chaves externo para o método interno usado pelo array de storage. A chave de segurança previamente definida para o gerenciamento de chaves externas passa a ser usada para o gerenciamento de chaves internas.

.Sobre esta tarefa
Nesta tarefa, você desativa o gerenciamento de chaves externas e baixa uma nova cópia de backup para o seu host local. A chave existente ainda é usada para Drive Security, mas será gerenciada internamente no array de storage.

.Passos
. Selecione o menu: configurações [Sistema].
. Em *Gerenciamento de chaves de segurança*, selecione *Desativar External Key Management*.
+
A caixa de diálogo Desativar gerenciamento de chaves externas é aberta.

. Em *Definir uma frase secreta/Reinserir frase secreta*, insira e confirme uma frase secreta para o backup da chave. O valor pode ter entre 8 e 32 caracteres e deve incluir cada um dos seguintes:
+
** Uma letra maiúscula (ou mais). Lembre-se de que a senha diferencia maiúsculas de minúsculas.
** Um número (um ou mais).
** Um caractere não alfanumérico, como !, *, @ (um ou mais).


+
[CAUTION]
====
Certifique-se de registrar suas anotações para uso posterior. Se precisar mover uma unidade com segurança habilitada do array de storage, você deverá saber o identificador e a frase secreta para desbloquear os dados da unidade.

====
. Clique em *Desativar*.
+
A chave de backup é baixada para o seu host local.

. Anote o identificador da chave, a frase secreta e o local do arquivo de chave baixado e, em seguida, clique em *Fechar*.


.Resultados
A segurança da unidade agora é gerenciada internamente pelo array de storage.

.Depois que você terminar
Você deve validar a chave de segurança para garantir que o arquivo de chave não esteja corrompido.
