---
permalink: sm-settings/use-ca-signed-certificates-for-authentication-with-a-key-management-server.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ca-signed, certificates, authentication, key, management, server, 
summary: Para garantir a comunicação segura entre um servidor de gerenciamento de chaves e os controladores do array de storage, você deve configurar os conjuntos de certificados apropriados. 
---
= Use certificados assinados por CA para autenticação com um servidor de gerenciamento de chaves no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para garantir a comunicação segura entre um servidor de gerenciamento de chaves e os controladores do array de storage, você deve configurar os conjuntos de certificados apropriados.

.Antes de começar
Você precisa estar conectado com um perfil de usuário que inclua permissões de Security admin. Caso contrário, as funções de certificado não aparecem.

.Sobre esta tarefa
A autenticação entre os controladores e um servidor de gerenciamento de chaves é um procedimento de duas etapas.



== Etapa 1: preencha e envie o CSR para autenticação com um servidor de gerenciamento de chaves

Primeiro, você deve gerar um arquivo de solicitação de assinatura de certificado (CSR) e, em seguida, usar o CSR para solicitar um certificado de cliente assinado de uma autoridade de certificação (CA) confiável pelo servidor de gerenciamento de chaves. Você também pode criar e baixar um certificado de cliente do servidor de gerenciamento de chaves usando o arquivo CSR baixado. Um certificado de cliente valida os controladores do array de storage, permitindo que o servidor de gerenciamento de chaves confie em suas solicitações do Key Management Interoperability Protocol (KMIP).


NOTE: Os arquivos CSR gerados externamente por meio de pares de chaves pública e privada podem ser importados através da caixa de diálogo Criar Chave de Segurança Externa. Para obter mais informações sobre como importar um arquivo CSR gerado externamente, consulte  https://docs.netapp.com/us-en/e-series-santricity/sm-settings/use-ca-signed-certificates-for-authentication-with-a-key-management-server.html#step-2-import-certificates-for-the-key-management-server["Etapa 2: importar certificados para o servidor de gerenciamento de chaves"].

.Passos
. Selecione menu:Configurações[Certificados].
. Na guia Key Management, selecione *Complete CSR*.
. Insira as seguintes informações:
+
** *Nome comum* -- Um nome que identifica o cliente. É prática comum que o nome comum corresponda aos requisitos do servidor KMS para convenções de nomenclatura de certificados de cliente. O nome comum geralmente ajuda o KMS a identificar o certificado do cliente quando este é apresentado durante um handshake.
** *Organização* -- O nome completo e legal da sua empresa ou organização. Inclua sufixos, como Inc. ou Corp.
** *Unidade organizacional (opcional)* -- A divisão da sua organização que está lidando com o certificado.
** *Cidade/Localidade* -- A cidade ou localidade onde sua organização está localizada.
** *Estado/Região (opcional)* -- O estado ou região onde sua organização está localizada.
** *Código ISO do país* -- O código ISO (International Organization for Standardization) de dois dígitos, como US, onde sua organização está localizada.


. Clique em *Download*.
+
Um arquivo CSR é salvo em seu sistema local.

. Solicite um certificado de cliente assinado pela CA que seja confiável para o servidor de gerenciamento de chaves.
+

NOTE: É comum que o servidor de gerenciamento de chaves possua um recurso que gera certificados assinados diretamente, pois funciona como sua própria CA.

. Quando você tiver um certificado de cliente, acesse <<Etapa 2: importar certificados para o servidor de gerenciamento de chaves>>.




== Etapa 2: importar certificados para o servidor de gerenciamento de chaves

Como próximo passo, você importa certificados para autenticação entre o array de storage e o servidor de gerenciamento de chaves. Existem dois tipos de certificados: o certificado do cliente valida os controladores do array de storage, enquanto o certificado do servidor de gerenciamento de chaves valida o servidor. Você deve carregar tanto o arquivo de certificado do cliente para os controladores quanto o arquivo de certificado do servidor para o servidor de gerenciamento de chaves.

.Antes de começar
* Você possui um arquivo de certificado de cliente assinado (consulte <<Etapa 1: preencha e envie o CSR para autenticação com um servidor de gerenciamento de chaves>>), e copiou esse arquivo para o host onde está acessando System Manager. Um certificado de cliente valida os controladores do array de storage, permitindo que o servidor de gerenciamento de chaves confie em suas solicitações do Key Management Interoperability Protocol (KMIP).
* Você deve obter um arquivo de certificado do servidor de gerenciamento de chaves e, em seguida, copiar esse arquivo para o host onde você está acessando System Manager. Um certificado de servidor de gerenciamento de chaves valida o servidor de gerenciamento de chaves, então o array de storage pode confiar em seu endereço IP. Você pode usar um certificado raiz, intermediário ou de servidor para o servidor de gerenciamento de chaves.
+
[NOTE]
====
Para obter mais informações sobre o certificado do servidor, consulte a documentação do seu key management server.

====


.Passos
. Selecione menu:Configurações[Certificados].
. Na guia Key Management, selecione *Import*.
+
Uma caixa de diálogo é aberta para importar os arquivos de certificado.

. Ao lado de *Selecionar certificado do cliente*, clique no botão *Procurar* para selecionar o arquivo de certificado do cliente para os controladores do array de storage.
+
O nome do arquivo é exibido na caixa de diálogo.

. Se você gerou um arquivo de certificado externamente usando um par de chaves privada e pública, clique no botão *Procurar* ao lado de *Selecionar arquivo de chave privada* para selecionar o arquivo de certificado para os controladores do array de storage.
+
O nome do arquivo é exibido na caixa de diálogo.

. Ao lado de *Selecionar certificado do servidor de gerenciamento de chaves*, clique no botão *Procurar* para selecionar o arquivo de certificado do servidor para o seu servidor de gerenciamento de chaves. Você pode escolher um certificado raiz, intermediário ou de servidor para o servidor de gerenciamento de chaves.
+
O nome do arquivo é exibido na caixa de diálogo.

. Clique em *Importar*.
+
Os arquivos são carregados e validados.


