---
permalink: sm-settings/view-iscsi-sessions-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, iscsi, sessions, 
summary: Você pode visualizar informações detalhadas sobre as conexões iSCSI com seu array de storage. As sessões iSCSI podem ocorrer com hosts ou arrays de storage remotos em uma relação de espelhamento assíncrono. 
---
= Visualizar sessões iSCSI no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode visualizar informações detalhadas sobre as conexões iSCSI com seu array de storage. As sessões iSCSI podem ocorrer com hosts ou arrays de storage remotos em uma relação de espelhamento assíncrono.

.Passos
. Selecione o menu: configurações [Sistema].
. Selecione *Visualizar/Encerrar sessões iSCSI*.
+
Uma lista das sessões iSCSI atuais aparece.

. *Opcional:* Para ver informações adicionais sobre uma sessão iSCSI específica, selecione uma sessão e clique em *Ver detalhes*.
+
.Detalhes do campo
[%collapsible]
====
[cols="25h,~"]
|===
| Item | Descrição 


 a| 
Identificador de sessão (SSID)
 a| 
Uma sequência hexadecimal que identifica uma sessão entre um iniciador iSCSI e um destino iSCSI. O SSID é composto pelo ISID e pelo TPGT.



 a| 
Session ID do iniciador (ISID)
 a| 
A parte do iniciador do identificador de sessão. O iniciador especifica o ISID durante o login.



 a| 
Grupo de portais alvo
 a| 
O destino iSCSI.



 a| 
Tag de grupo de portal de destino (TPGT)
 a| 
A parte de destino do identificador de sessão. Um identificador numérico de 16 bits para um grupo de portais de destino iSCSI.



 a| 
Nome do iniciador iSCSI
 a| 
O nome exclusivo mundial do iniciador.



 a| 
Rótulo do iniciador iSCSI
 a| 
O rótulo do usuário definido no System Manager.



 a| 
Alias do iniciador iSCSI
 a| 
Um nome que também pode ser associado a um nó iSCSI. O alias permite que uma organização associe uma string amigável ao nome iSCSI. No entanto, o alias não substitui o nome iSCSI. O alias do iniciador iSCSI só pode ser definido no host, não no System Manager



 a| 
Host
 a| 
Um servidor que envia entrada e saída para o array de storage.



 a| 
ID de conexão (CID)
 a| 
Um nome único para uma conexão dentro da sessão entre o iniciador e o destino. O iniciador gera esse ID e o apresenta ao destino durante solicitações de login. O ID da conexão também é apresentado durante logouts que encerram conexões.



 a| 
Identificador da porta
 a| 
A porta do controlador associada à conexão.



 a| 
Endereço IP do iniciador
 a| 
O endereço IP do iniciador.



 a| 
Parâmetros de login negociados
 a| 
Os parâmetros que são transacionados durante o login da sessão iSCSI.



 a| 
Método de autenticação
 a| 
A técnica para autenticar usuários que desejam acessar a rede iSCSI. Os valores válidos são *CHAP* e *None*.



 a| 
Método de resumo do cabeçalho
 a| 
A técnica para exibir os possíveis valores de cabeçalho para a sessão iSCSI. HeaderDigest e DataDigest podem ser *None* ou *CRC32C*. O valor padrão para ambos é *None*.



 a| 
Método de resumo de dados
 a| 
A técnica para exibir os possíveis valores de dados para a sessão iSCSI. HeaderDigest e DataDigest podem ser *None* ou *CRC32C*. O valor padrão para ambos é *None*.



 a| 
Conexões máximas
 a| 
O maior número de conexões permitido para a sessão iSCSI. O número máximo de conexões pode ser de 1 a 4. O valor padrão é *1*.



 a| 
Alias de destino
 a| 
O rótulo associado ao destino.



 a| 
Alias do iniciador
 a| 
O rótulo associado ao iniciador.



 a| 
Endereço IP de destino
 a| 
O endereço IP do destino para a sessão iSCSI. Nomes DNS não são suportados.



 a| 
R2T inicial
 a| 
O status inicial de pronto para transferência. O status pode ser *Sim* ou *Não*.



 a| 
Comprimento máximo de rajada
 a| 
A carga máxima SCSI em bytes para esta sessão iSCSI. O comprimento máximo do burst pode ser de 512 a 262.144 (256 KB). O valor padrão é *262.144 (256 KB)*.



 a| 
Primeira duração da rajada
 a| 
A carga SCSI em bytes para dados não solicitados para esta sessão iSCSI. O comprimento da primeira rajada pode ser de 512 a 131.072 (128 KB). O valor padrão é *65.536 (64 KB)*.



 a| 
Tempo de espera padrão
 a| 
O número mínimo de segundos a aguardar antes de tentar estabelecer uma conexão após o término ou a reinicialização de uma conexão. O valor padrão para o tempo de espera pode variar de 0 a 3600. O padrão é *2*.



 a| 
Tempo padrão de retenção
 a| 
O número máximo de segundos que a conexão ainda é possível após o término ou a reinicialização da conexão. O tempo padrão de retenção pode ser de 0 a 3600. O valor padrão é *20*.



 a| 
Máximo de R2T pendente
 a| 
O número máximo de "prontos para transferência" pendentes para esta sessão iSCSI. O valor máximo de prontos para transferência pendentes pode ser de 1 a 16. O padrão é *1*.



 a| 
Nível de recuperação de erros
 a| 
O nível de recuperação de erros para esta sessão iSCSI. O valor do nível de recuperação de erros é sempre definido como *0*.



 a| 
Comprimento máximo do segmento de dados recebidos
 a| 
A quantidade máxima de dados que o iniciador ou o destino podem receber em qualquer unidade de dados de carga (PDU) iSCSI.



 a| 
Nome do destino
 a| 
O nome oficial do destino (não o pseudônimo). O nome do destino no formato _iqn_.



 a| 
Nome do iniciador
 a| 
O nome oficial do iniciador (não o alias). O nome do iniciador que usa o formato _iqn_ ou _eui_.

|===
====
. *Opcional:* Para salvar o relatório em um arquivo, clique em *Save*.
+
O arquivo está salvo na pasta Downloads do seu navegador com o nome de arquivo `iscsi-session-connections.txt`.


