---
permalink: sm-support/collect-support-data-manually.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, collect, support, data, manually 
summary: Você pode reunir diversos tipos de dados de inventário, status e desempenho do seu array de storage em um único arquivo. O suporte técnico pode usar o arquivo para solucionar problemas e realizar análises adicionais. 
---
= Coletar dados de suporte manualmente no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode reunir diversos tipos de dados de inventário, status e desempenho do seu array de storage em um único arquivo. O suporte técnico pode usar o arquivo para solucionar problemas e realizar análises adicionais.

.Sobre esta tarefa
++ ++

[NOTE]
====
Se o recurso AutoSupport estiver ativado, você também pode coletar esses dados acessando a guia *AutoSupport* e selecionando *Enviar despacho de AutoSupport*.

====
Você só pode executar uma operação de coleta por vez. Se tentar iniciar outra operação, você receberá uma mensagem de erro.

[NOTE]
====
Execute esta operação somente quando instruído a fazê-lo pelo suporte técnico.

====
.Passos
. Selecione menu: guia Suporte [Support Center > Diagnostics].
. Selecione *Collect Support Data*.
. Clique em *Coletar*.
+
O arquivo é salvo na pasta Downloads do seu navegador com o nome `support-data.7z`. Se sua estante contiver gavetas, os dados de diagnóstico dessa estante são arquivados em um arquivo zipado separado chamado `tray-component-state-capture.7z`.

. Siga as instruções fornecidas pelo suporte técnico para enviar o arquivo para eles.

