---
permalink: sm-support/disable-autosupport-maintenance-window.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, disable, autosupport, ASUP, maintenance window 
summary: Desative a janela de manutenção do AutoSupport para permitir a criação automática de chamados em eventos de erro. Quando a janela de manutenção do AutoSupport estiver desativada, o array de storage usará o AutoSupport para abrir um chamado com o suporte se houver um problema. 
---
= Desative a janela de manutenção do AutoSupport no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Desative a janela de manutenção do AutoSupport para permitir a criação automática de chamados em eventos de erro. Quando a janela de manutenção do AutoSupport estiver desativada, o array de storage usará o AutoSupport para abrir um chamado com o suporte se houver um problema.

.Passos
. Selecione o menu:Suporte [Support Center > AutoSupport] tab.
. Selecione *Desativar AutoSupport Maintenance window*.
. Insira o endereço de e-mail para receber uma confirmação de que a solicitação para desativar a janela de manutenção foi processada.
+
Dependendo da sua configuração, você pode inserir até cinco endereços de e-mail. Se quiser adicionar mais de um endereço, selecione *Adicionar outro e-mail* para abrir outro campo.

. Clique em *Yes*.
+
AutoSupport a criação automática de tickets em eventos de erro está ativada.



.Depois que você terminar
A janela de manutenção não terminará até que a solicitação do array de storage tenha sido processada pelos servidores AutoSupport. Aguarde até receber um e-mail de confirmação antes de prosseguir.
