---
permalink: sm-support/overview-support.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, support, center 
summary: Utilize o Support Center para realizar operações de diagnóstico, recuperação e coleta de informações que possam ser solicitadas pelo suporte técnico. 
---
= Obtenha suporte no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A página de Suporte fornece acesso a recursos de suporte técnico.



== Quais tarefas de suporte estão disponíveis?

Na seção Suporte, você pode visualizar contatos de suporte técnico, realizar diagnósticos, configurar AutoSupport, visualizar o registro de eventos e realizar atualizações de software.

Saiba mais:

* link:autosupport-feature-overview.html["AutoSupport visão geral do recurso"]
* link:overview-event-log.html["Visão geral do log de eventos"]
* link:overview-upgrade-center.html["Visão geral do Upgrade Center"]




== Como faço para entrar em contato com o suporte técnico?

Na página principal, clique em menu:Support[Support Center > guia Support Resources]. As informações de contato do suporte técnico estão listadas no canto superior direito da interface.
