---
permalink: sm-support/view-events-using-the-event-log.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, events, 
summary: Você pode visualizar o registro de eventos, que fornece um histórico de eventos que ocorreram no array de storage. 
---
= Visualize eventos usando o registro de eventos no SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode visualizar o registro de eventos, que fornece um histórico de eventos que ocorreram no array de storage.

.Passos
. Selecione o menu: suporte [Registro de eventos].
+
A página de log de eventos é exibida.

+
.Detalhes da página
[%collapsible]
====
[cols="25h,~"]
|===
| Item | Descrição 


 a| 
Ver todos os campos
 a| 
Alterna entre todos os eventos e apenas os eventos críticos e de aviso.



 a| 
Campo de filtro
 a| 
Filtra os eventos. Útil para exibir apenas eventos relacionados a um componente específico, um evento específico, etc.



 a| 
Selecione o ícone de colunas.
 a| 
Permite selecionar outras colunas para visualizar. Outras colunas fornecem informações adicionais sobre o evento.



 a| 
Caixas de seleção
 a| 
Permite selecionar os eventos a serem salvos. A caixa de seleção no cabeçalho da tabela seleciona todos os eventos.



 a| 
Coluna Data/Hora
 a| 
A data e o carimbo de hora do evento, de acordo com o relógio do controlador.


NOTE: Inicialmente, o registro de eventos classifica os eventos com base no número de sequência. Normalmente, essa sequência corresponde à data e hora. No entanto, os dois relógios do controlador no array de storage podem estar dessincronizados. Nesse caso, algumas inconsistências percebidas podem aparecer no registro de eventos em relação aos eventos e à data e hora exibidas.



 a| 
Coluna de prioridade
 a| 
Estes valores de prioridade existem:

** *Crítico* -- Existe um problema com o array de storage. No entanto, se você agir imediatamente, poderá evitar perder o acesso aos dados. Eventos críticos são usados para notificações de alerta. Todos os eventos críticos são enviados para qualquer cliente de gerenciamento de rede (por meio de traps SNMP) ou para o destinatário de e-mail que você configurou.
** *Aviso* -- Ocorreu um erro que degradou o desempenho e a capacidade do array de storage de recuperar-se de outro erro.
** *Informativo* -- Informações não críticas relacionadas ao array de storage.




 a| 
Coluna Tipo de componente
 a| 
O componente afetado pelo evento. O componente pode ser hardware, como um drive ou um controlador, ou pode ser software, como firmware do controlador.



 a| 
Coluna de localização do componente
 a| 
A localização física do componente no array de storage.



 a| 
Coluna Description
 a| 
Uma descrição do evento.

*Exemplo* -- `Drive write failure - retries exhausted`



 a| 
Coluna Número de sequência
 a| 
Um número de 64 bits que identifica exclusivamente uma entrada de log específica para um array de storage. Esse número é incrementado em um a cada nova entrada de log de eventos. Para exibir essa informação, clique no ícone *Selecionar colunas*.



 a| 
Coluna Event Type
 a| 
Um número de 4 dígitos que identifica cada tipo de evento registrado. Para exibir essas informações, clique no ícone *Selecionar colunas*.



 a| 
Coluna de códigos específicos do evento
 a| 
Essas informações são utilizadas pelo suporte técnico. Para exibir essas informações, clique no ícone *Selecionar colunas*.



 a| 
Coluna Categoria de Evento
 a| 
** **Falha** – Um componente no array de storage apresentou falha; por exemplo, falha na drive ou falha na bateria.
** **Alteração de estado** – Um elemento do array de storage que teve seu estado alterado; por exemplo, um volume passou para o status Optimal ou um controlador passou para o status Offline.
** **Interno** – Operações internas do controlador que não exigem ação do usuário; por exemplo, o controlador concluiu start-of-day.
** **Comando** – Um comando que foi emitido para o array de storage; por exemplo, um hot spare foi atribuído.
** **Erro** – Foi detectada uma condição de erro no array de storage; por exemplo, um controlador não consegue sincronizar e limpar o cache, ou um erro de redundância é detectado no array de storage.
** **Geral** – Qualquer evento que não se encaixe bem em nenhuma outra categoria. Para exibir essas informações, clique no ícone **Select columns**.




 a| 
Coluna Logged By
 a| 
O nome do controlador que registrou o evento. Para exibir essas informações, clique no ícone **Select columns**.

|===
====
. Para recuperar novos eventos do array de storage, clique em **Refresh**.
+
Pode levar alguns minutos para que um evento seja registrado e se torne visível na página Event Log.

. Para salvar o registro de eventos em um arquivo:
+
.. Selecione a caixa de seleção ao lado de cada evento que você deseja salvar.
.. Clique em *Salvar*.
+
O arquivo é salvo na pasta Downloads do seu navegador com o nome  `major-event-log-timestamp.log`.



. Para limpar eventos do registro de eventos:
+
O registro de eventos armazena aproximadamente 8.000 eventos antes de substituir um evento por um novo. Se você quiser manter os eventos, pode salvá-los e removê-los do registro de eventos.

+
.. Primeiro, salve o log de eventos.
.. Clique em *Limpar tudo* e confirme que deseja realizar a operação.



