---
permalink: um-certificates/access-management-with-saml.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, access management, saml 
summary: 'Para o gerenciamento de acesso, os administradores podem usar os recursos do Security Assertion Markup Language (SAML) 2.0 incorporados no array.' 
---
= Gerenciamento de acesso com SAML no SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para o gerenciamento de acesso, os administradores podem usar os recursos do Security Assertion Markup Language (SAML) 2.0 incorporados no array.



== Fluxo de trabalho de configuração

A configuração SAML funciona da seguinte forma:

. Um administrador faz login no Unified Manager com um perfil de usuário que inclui permissões de Security Admin.
+
[NOTE]
====
O `admin` usuário tem acesso total a todas as funções no System Manager.

====
. O administrador vai para a guia *SAML* em Gerenciamento de Acesso.
. Um administrador configura a comunicação com o Identity Provider (IdP). Um IdP é um sistema externo usado para solicitar credenciais de um usuário e determinar se o usuário foi autenticado com sucesso. Para configurar a comunicação com o array de storage, o administrador baixa o arquivo de metadados do IdP do sistema IdP e, em seguida, usa Unified Manager para carregar o arquivo no array de storage.
. Um administrador estabelece uma relação de confiança entre o Service Provider e o IdP. Um Service Provider controla a autorização do usuário; neste caso, o controlador no array de storage atua como o Service Provider. Para configurar as comunicações, o administrador usa Unified Manager para exportar um arquivo de metadados do Service Provider para o controlador. A partir do sistema IdP, o administrador então importa o arquivo de metadados para o IdP.
+
[NOTE]
====
Os administradores também devem garantir que o IdP suporte a capacidade de retornar um Name ID na autenticação.

====
. O administrador mapeia as funções do array de storage para os atributos de usuário definidos no IdP. Para isso, o administrador usa Unified Manager para criar os mapeamentos.
. O administrador testa o login SSO no URL do IdP. Este teste garante que o array de storage e o IdP possam se comunicar.
+
[CAUTION]
====
Uma vez que o SAML esteja ativado, você _não_ pode desativá-lo através da interface de usuário, nem editar as configurações do IdP. Se precisar desativar ou editar a configuração do SAML, entre em contato com o Technical Support para obter assistência.

====
. No Unified Manager, o administrador habilita o SAML para o array de storage.
. Os usuários acessam o sistema com suas credenciais de SSO.




== Gerenciamento

Ao usar SAML para autenticação, os administradores podem executar as seguintes tarefas de gerenciamento:

* Modificar ou criar novo mapeamento de funções
* Exportar arquivos do provedor de serviços




== Restrições de acesso

Quando o SAML está ativado, os usuários não podem descobrir ou gerenciar o armazenamento desse array a partir da interface Storage Manager legada.

Além disso, os seguintes clientes não podem acessar os serviços e recursos do array de storage:

* Janela de gerenciamento empresarial (EMW)
* Interface de linha de comando (CLI)
* Clientes de Software Developer Kits (SDK)
* Clientes in-band
* Clientes de API REST com autenticação básica HTTP
* Faça login usando o endpoint padrão da API REST

