---
permalink: um-certificates/change-local-user-passwords-settings-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, local, user, password, settings 
summary: Você pode definir o comprimento mínimo exigido para todas as novas senhas de usuários locais ou senhas de usuários locais atualizadas. Você também pode permitir que usuários locais acessem o sistema sem digitar uma senha. 
---
= Alterar as configurações de senha do usuário local em SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode definir o comprimento mínimo exigido para todas as novas senhas de usuários locais ou senhas de usuários locais atualizadas. Você também pode permitir que usuários locais acessem o sistema sem digitar uma senha.

.Antes de começar
Você deve estar conectado como administrador local, o que inclui permissões de Root admin.

.Sobre esta tarefa
Mantenha estas diretrizes em mente ao definir o comprimento mínimo para senhas de usuários locais:

* As alterações de configuração não afetam as senhas de usuários locais existentes.
* A configuração de comprimento mínimo exigido para senhas de usuários locais deve estar entre 0 e 30 caracteres.
* Quaisquer novas senhas de usuários locais devem atender ou exceder a configuração atual de comprimento mínimo.
* Não defina um comprimento mínimo para a senha se desejar que os usuários locais acessem o sistema sem inserir uma senha.


.Passos
. Selecione *Access Management*.
. Selecione a guia *Funções de usuário local*.
. Selecione *Visualizar/Editar Settings*.
+
A caixa de diálogo Configurações de senha do usuário local é aberta.

. Faça uma das seguintes ações:
+
** Para permitir que os usuários locais acessem o sistema _sem_ inserir uma senha, desmarque a caixa de seleção "Exigir que todas as senhas de usuários locais tenham pelo menos".
** Para definir um comprimento mínimo de senha para todas as senhas de usuários locais, selecione a caixa de seleção "Exigir que todas as senhas de usuários locais tenham pelo menos" e então use a caixa de rotação para definir o comprimento mínimo exigido para todas as senhas de usuários locais.
+
Quaisquer novas senhas de usuários locais devem atender ou exceder a configuração atual.



. Clique em *Salvar*.

