---
permalink: um-certificates/change-passwords-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, passwords 
summary: Você pode alterar as senhas de usuário para cada usuário em Access Management. 
---
= Alterar senhas para perfis de usuário locais no SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar as senhas de usuário para cada usuário em Access Management.

.Antes de começar
* Você deve estar conectado como administrador local, o que inclui permissões de Root admin.
* Você deve saber a senha do administrador local.


.Sobre esta tarefa
Mantenha estas diretrizes em mente ao escolher uma senha:

* Quaisquer novas senhas de usuários locais devem atender ou exceder a configuração atual para senha mínima (em Exibir/Editar Configurações).
* As senhas diferenciam maiúsculas de minúsculas.
* Os espaços em branco no final das senhas não são removidos durante a sua criação. Certifique-se de incluir os espaços caso eles estejam presentes na senha.
* Para maior segurança, use pelo menos 15 caracteres alfanuméricos e altere a senha com frequência.


.Passos
. Selecione *Access Management*.
. Selecione a guia *Funções de usuário local*.
. Selecione um usuário da tabela.
+
O botão Alterar Senha se torna disponível.

. Selecione *Change Password*.
+
A caixa de diálogo Alterar Senha é aberta.

. Se não houver um comprimento mínimo de senha definido para senhas de usuários locais, você pode selecionar a caixa de seleção para exigir que o usuário insira uma senha para acessar o sistema.
. Insira a nova senha para o usuário selecionado nos dois campos.
. Digite sua senha de administrador local para confirmar esta operação e clique em *Alterar*.


.Resultados
Se o usuário estiver conectado no momento, a alteração da senha faz com que a sessão ativa do usuário seja encerrada.
