---
permalink: um-certificates/faq-user-access-mgmt-um.html 
sidebar: sidebar 
keywords:  
summary: Esta FAQ pode ajudar se você estiver apenas procurando uma resposta rápida para uma pergunta. 
---
= Perguntas frequentes sobre gerenciamento de acesso de usuário para SANtricity Unified Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta FAQ pode ajudar se você estiver apenas procurando uma resposta rápida para uma pergunta.



== Por que não consigo fazer login?

Se você receber um erro ao tentar fazer login, revise estas possíveis causas.

Os erros de login podem ocorrer por um destes motivos:

* Você digitou um nome de usuário ou senha incorreto.
* Você não possui privilégios suficientes.
* Você tentou fazer login várias vezes sem sucesso, o que ativou o modo de bloqueio. Aguarde 10 minutos para fazer login novamente.
* A autenticação SAML está ativada. Atualize seu navegador para fazer login.




== O que preciso saber antes de adicionar um servidor de diretório?

Antes de adicionar um servidor de diretório em Access Management, você deve atender a certos requisitos.

* Os grupos de usuários devem ser definidos no seu serviço de diretório.
* As credenciais do servidor LDAP devem estar disponíveis, incluindo o nome de domínio, o URL do servidor e, opcionalmente, o nome de usuário e a senha da conta de vinculação.
* Para servidores LDAPS que utilizam um protocolo seguro, a cadeia de certificados do servidor LDAP deve estar instalada em sua máquina local.




== O que preciso saber sobre o mapeamento para funções de array de storage?

Antes de associar grupos a funções, revise as diretrizes.

As funcionalidades do RBAC (controle de acesso baseado em funções) incluem as seguintes funções:

* *Administrador de armazenamento* -- acesso completo de leitura/gravação aos objetos de armazenamento nos arrays, mas sem acesso à configuração de segurança.
* *Administrador de segurança* -- Acesso à configuração de segurança em Access Management e Certificate Management.
* *Administrador de suporte* -- Acesso a todos os recursos de hardware em arrays de storage, dados de falhas e eventos MEL. Sem acesso a objetos de storage ou à configuração de segurança.
* *Monitor* -- Acesso somente leitura a todos os objetos de storage, mas sem acesso à configuração de segurança.


[NOTE]
====
A função Monitor é obrigatória para todos os usuários, incluindo o administrador.

====
Se você estiver usando um servidor LDAP (Lightweight Directory Access Protocol) e Directory Services, certifique-se de que:

* Um administrador definiu grupos de usuários no serviço de diretório.
* Você conhece os nomes de domínio dos grupos de usuários LDAP.




=== SAML

Se você estiver usando os recursos de Security Assertion Markup Language (SAML) incorporados no array de storage, certifique-se de que:

* Um administrador do Identity Provider (IdP) configurou os atributos do usuário e a associação a grupos no sistema IdP.
* Você conhece os nomes de associação do grupo.
* Você conhece o valor do atributo para o grupo a ser mapeado. Expressões regulares são suportadas. Esses caracteres especiais de expressão regular devem ser escapados com uma barra invertida (`\` se não fizerem parte de um padrão de expressão regular:
+
[listing]
----
\.[]{}()<>*+-=!?^$|
----
* A função de Monitor é obrigatória para todos os usuários, incluindo o administrador. Unified Manager não funcionará corretamente para nenhum usuário sem a função de Monitor presente.




== O que preciso saber antes de configurar e habilitar o SAML?

Antes de configurar e ativar os recursos do Security Assertion Markup Language (SAML) para autenticação, certifique-se de atender aos seguintes requisitos e compreender as restrições do SAML.



=== Requisitos

Antes de começar, certifique-se de que:

* Um Provedor de Identidade (IdP) está configurado em sua rede. Um IdP é um sistema externo usado para solicitar credenciais de um usuário e determinar se o usuário foi autenticado com sucesso. Sua equipe de segurança é responsável por manter o IdP.
* Um administrador do IdP configurou atributos de usuário e grupos no sistema IdP.
* Um administrador do IdP garantiu que o IdP suporta a capacidade de retornar um Name ID na autenticação.
* Um administrador assegurou que o servidor IdP e o relógio do controlador estão sincronizados (seja por meio de um servidor NTP ou ajustando as configurações do relógio do controlador).
* Um arquivo de metadados do IdP é baixado do sistema IdP e fica disponível no sistema local usado para acessar Unified Manager.
* Você sabe o endereço IP ou nome de domínio do controlador no array de storage.




=== Restrições

Além dos requisitos acima, certifique-se de entender as seguintes restrições:

* Uma vez que o SAML esteja habilitado, você _não_ pode desabilitá-lo através da interface de usuário, nem editar as configurações do IdP. Se você precisar desabilitar ou editar a configuração do SAML, entre em contato com o suporte técnico para obter assistência. Recomendamos que você teste os logins SSO antes de habilitar o SAML na etapa final de configuração. (O sistema também realiza um teste de login SSO antes de habilitar o SAML.)
* Se você desativar o SAML no futuro, o sistema restaurará automaticamente a configuração anterior (Local User Roles e/ou Directory Services).
* Se os Serviços de Diretório estiverem configurados atualmente para autenticação de usuário, o SAML substituirá essa configuração.
* Quando o SAML está configurado, os seguintes clientes não podem acessar os recursos do array de storage:
+
** Janela de gerenciamento empresarial (EMW)
** Interface de linha de comando (CLI)
** Clientes de Software Developer Kits (SDK)
** Clientes in-band
** Clientes de API REST com autenticação básica HTTP
** Faça login usando o endpoint padrão da API REST






== Quais são os usuários locais?

Os usuários locais são predefinidos no sistema e incluem permissões específicas.

Usuários locais incluem:

* *admin* -- Superadministrador com acesso a todas as funções no sistema. Este usuário inclui todas as funções. A senha deve ser definida no primeiro acesso.
* *storage* -- O administrador responsável por todo o provisionamento de storage. Este usuário inclui as seguintes funções: Storage Admin, Support Admin e Monitor. Esta conta fica desativada até que uma senha seja definida.
* *security* -- O usuário responsável pela configuração de segurança, incluindo Access Management e Certificate Management. Este usuário inclui as seguintes funções: Security Admin e Monitor. Esta conta fica desativada até que uma senha seja definida.
* *support* -- O usuário responsável pelos recursos de hardware, dados de falhas e upgrades de firmware. Este usuário inclui as seguintes funções: Support Admin e Monitor. Esta conta fica desativada até que uma senha seja definida.
* *monitor* -- Um usuário com acesso somente leitura ao sistema. Este usuário inclui apenas a função Monitor. Esta conta fica desativada até que uma senha seja definida.
* *rw* (leitura/gravação) -- Este usuário inclui as seguintes funções: Storage Admin, Support Admin e Monitor. Esta conta está desativada até que uma senha seja definida.
* *ro* (somente leitura) -- Este usuário inclui apenas a função Monitor. Esta conta está desativada até que uma senha seja definida.

