---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, administrator, password, protection 
summary: Você deve configurar SANtricity Unified Manager com uma senha de administrador para protegê-lo contra acesso não autorizado. 
---
= Saiba mais sobre a proteção por senha de administrador no SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar SANtricity Unified Manager com uma senha de administrador para protegê-lo contra acesso não autorizado.



== Senha de administrador e perfis de usuário

Ao iniciar Unified Manager pela primeira vez, você será solicitado a definir uma senha de administrador. Qualquer usuário que possua a senha de administrador pode fazer alterações de configuração nos arrays de storage.

Além da senha de administrador, a interface Unified Manager inclui perfis de usuário pré-configurados com uma ou mais funções atribuídas a eles. Para obter mais informações, consulte link:../um-certificates/how-access-management-works-unified.html["Como funciona o gerenciamento de acessos"].

Os usuários e os mapeamentos não podem ser alterados. Somente as senhas podem ser modificadas. Para alterar as senhas, consulte:

* link:change-admin-password-unified.html["Alterar a senha do admin"]
* link:../um-certificates/change-passwords-unified.html["Alterar senhas para perfis de usuário locais"]




== Tempo limite da sessão

O software solicita a senha apenas uma vez durante uma sessão de gerenciamento. Uma sessão expira após 30 minutos de inatividade por padrão, momento em que você deve inserir a senha novamente. Se outro usuário acessar o software a partir de outro cliente de gerenciamento e alterar a senha enquanto sua sessão estiver em andamento, você será solicitado a inserir a senha na próxima vez que tentar realizar uma operação de configuração ou de visualização.

Por motivos de segurança, você só pode tentar inserir uma senha cinco vezes antes que o software entre em estado de "bloqueio". Nesse estado, o software rejeita tentativas subsequentes de senha. Você deve aguardar 10 minutos para redefinir para o estado "normal" antes de tentar inserir uma senha novamente.

Você pode ajustar os tempos limite da sessão ou pode desativar os tempos limite da sessão completamente. Para obter mais informações, consulte link:manage-session-timeouts-unified.html["Gerenciar tempos limite de sessão"].
