---
permalink: um-admin/change-storage-array-passwords.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, storage, array, passwords 
summary: Você pode atualizar as senhas usadas para visualizar e acessar arrays de storage no SANtricity Unified Manager. 
---
= Alterar senhas do array de storage no SANtricity Unified Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atualizar as senhas usadas para visualizar e acessar arrays de storage no SANtricity Unified Manager.

.Antes de começar
* Você deve estar conectado com um perfil de usuário que inclua permissões de Storage admin.
* Você deve saber a senha atual do array de storage, que é definida no System Manager.


.Sobre esta tarefa
Nesta tarefa, você insere a senha atual de um array de storage para poder acessá-lo no Unified Manager. Isso pode ser necessário se a senha do array foi alterada no System Manager e agora também precisa ser alterada no Unified Manager.

.Passos
. Na página Manage, selecione um ou mais arrays de storage.
. Selecione o menu: tarefas incomuns [Fornecer senhas do array de armazenamento].
. Insira a senha ou senhas para cada array de storage e, em seguida, clique em *Salvar*.

