---
permalink: um-admin/change-admin-password-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, admin, password 
summary: Você pode alterar a senha de admin usada para acessar SANtricity Unified Manager. 
---
= Alterar a senha do admin no SANtricity Unified Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar a senha de admin usada para acessar SANtricity Unified Manager.

.Antes de começar
* Você deve estar conectado como administrador local, o que inclui permissões de Root admin.
* Você deve saber a senha de administrador atual.


.Sobre esta tarefa
Mantenha estas diretrizes em mente ao escolher uma senha:

* As senhas diferenciam maiúsculas de minúsculas.
* Os espaços em branco no final das senhas não são removidos durante a sua criação. Certifique-se de incluir os espaços caso eles estejam presentes na senha.
* Para maior segurança, use pelo menos 15 caracteres alfanuméricos e altere a senha com frequência.


.Passos
. Selecione o menu: Configurações [Access Management].
. Selecione a guia *Funções de usuário local*.
. Selecione o usuário *admin* na tabela.
+
O botão Alterar Senha se torna disponível.

. Selecione *Change Password*.
+
A caixa de diálogo Alterar Senha é aberta.

. Se não houver um comprimento mínimo de senha definido para senhas de usuários locais, selecione a caixa de seleção para exigir que o usuário insira uma senha para acessar o sistema.
. Digite a nova senha nos dois campos.
. Digite sua senha de administrador local para confirmar esta operação e clique em *Alterar*.

