---
permalink: um-admin/manage-session-timeouts-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, manage, session, timeouts 
summary: Você pode configurar tempos limite para SANtricity Unified Manager, para que as sessões inativas dos usuários sejam desconectadas após um período especificado. 
---
= Gerenciar os tempos limite de sessão no SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar tempos limite para SANtricity Unified Manager, para que as sessões inativas dos usuários sejam desconectadas após um tempo especificado.

.Sobre esta tarefa
Por padrão, o tempo limite da sessão para Unified Manager é de 30 minutos. Você pode ajustar esse tempo ou pode desativar completamente os tempos limite de sessão.


NOTE: Se o Access Management estiver configurado usando os recursos de Security Assertion Markup Language (SAML) incorporados no array, pode ocorrer um tempo limite de sessão quando a sessão SSO do usuário atingir seu limite máximo. Isso pode ocorrer antes do tempo limite da sessão do System Manager.

.Passos
. Na barra de menus, selecione a seta suspensa ao lado do seu nome de login de usuário.
. Selecione *Ativar/Desativar tempo limite de sessão*.
+
A caixa de diálogo Ativar/Desativar Tempo Limite da Sessão é aberta.

. Use os controles giratórios para aumentar ou diminuir o tempo em minutos.
+
O tempo limite mínimo que você pode definir é 15 minutos.

+
[NOTE]
====
Para desativar os tempos limite de sessão, desmarque a caixa de seleção *Definir o tempo de...*.

====
. Clique em *Salvar*.

